with-expecter: true
disable-version-string: true
resolve-type-alias: false
issue-845-fix: true
packages:
  github.com/itsLeonB/cardstack/backend/internal/adapters/repository:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
      filename: "{{.InterfaceName}}.go"
    interfaces:
      CatalogRepository:
