with-expecter: true
disable-version-string: true
resolve-type-alias: false
issue-845-fix: true
dir: "internal/mocks"
outpkg: mocks
filename: "{{.InterfaceName}}.go"
packages:
  github.com/itsLeonB/cardstack/backend/internal/core/embedding:
    interfaces:
      BatchEmbedder:
      ImageEmbedder:
      ImageFetcher:
  github.com/itsLeonB/cardstack/backend/internal/core/objectstore:
    interfaces:
      ObjectStore:
  github.com/itsLeonB/cardstack/backend/internal/domain/repository:
    interfaces:
      CatalogRepository:
      CollectionRepository:
      EmbeddingRepository:
      ExpansionSetRepository:
      InventoryRepository:
      MatchRepository:
      UserRepository:
  github.com/itsLeonB/cardstack/backend/internal/domain/service:
    interfaces:
      CatalogService:
      CollectionService:
      InventoryService:
      MatchService:
      UserService:
      IdentityCache:
  github.com/itsLeonB/cardstack/backend/internal/adapters/http/auth:
    interfaces:
      KeySource:
      TokenVerifier:
  github.com/itsLeonB/go-crud:
    interfaces:
      Repository:
      Transactor:
