// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	embedding "github.com/itsLeonB/cardstack/backend/internal/core/embedding"
	mock "github.com/stretchr/testify/mock"
)

// MockBatchEmbedder is an autogenerated mock type for the BatchEmbedder type
type MockBatchEmbedder struct {
	mock.Mock
}

type MockBatchEmbedder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBatchEmbedder) EXPECT() *MockBatchEmbedder_Expecter {
	return &MockBatchEmbedder_Expecter{mock: &_m.Mock}
}

// Collect provides a mock function with given fields: ctx, job
func (_m *MockBatchEmbedder) Collect(ctx context.Context, job string) (embedding.Outcome, error) {
	ret := _m.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for Collect")
	}

	var r0 embedding.Outcome
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (embedding.Outcome, error)); ok {
		return rf(ctx, job)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) embedding.Outcome); ok {
		r0 = rf(ctx, job)
	} else {
		r0 = ret.Get(0).(embedding.Outcome)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, job)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBatchEmbedder_Collect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Collect'
type MockBatchEmbedder_Collect_Call struct {
	*mock.Call
}

// Collect is a helper method to define mock.On call
//   - ctx context.Context
//   - job string
func (_e *MockBatchEmbedder_Expecter) Collect(ctx interface{}, job interface{}) *MockBatchEmbedder_Collect_Call {
	return &MockBatchEmbedder_Collect_Call{Call: _e.mock.On("Collect", ctx, job)}
}

func (_c *MockBatchEmbedder_Collect_Call) Run(run func(ctx context.Context, job string)) *MockBatchEmbedder_Collect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBatchEmbedder_Collect_Call) Return(_a0 embedding.Outcome, _a1 error) *MockBatchEmbedder_Collect_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBatchEmbedder_Collect_Call) RunAndReturn(run func(context.Context, string) (embedding.Outcome, error)) *MockBatchEmbedder_Collect_Call {
	_c.Call.Return(run)
	return _c
}

// Submit provides a mock function with given fields: ctx, images
func (_m *MockBatchEmbedder) Submit(ctx context.Context, images []embedding.Image) (string, error) {
	ret := _m.Called(ctx, images)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []embedding.Image) (string, error)); ok {
		return rf(ctx, images)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []embedding.Image) string); ok {
		r0 = rf(ctx, images)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []embedding.Image) error); ok {
		r1 = rf(ctx, images)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBatchEmbedder_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type MockBatchEmbedder_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - ctx context.Context
//   - images []embedding.Image
func (_e *MockBatchEmbedder_Expecter) Submit(ctx interface{}, images interface{}) *MockBatchEmbedder_Submit_Call {
	return &MockBatchEmbedder_Submit_Call{Call: _e.mock.On("Submit", ctx, images)}
}

func (_c *MockBatchEmbedder_Submit_Call) Run(run func(ctx context.Context, images []embedding.Image)) *MockBatchEmbedder_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]embedding.Image))
	})
	return _c
}

func (_c *MockBatchEmbedder_Submit_Call) Return(_a0 string, _a1 error) *MockBatchEmbedder_Submit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBatchEmbedder_Submit_Call) RunAndReturn(run func(context.Context, []embedding.Image) (string, error)) *MockBatchEmbedder_Submit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBatchEmbedder creates a new instance of MockBatchEmbedder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBatchEmbedder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBatchEmbedder {
	mock := &MockBatchEmbedder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
