// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/itsLeonB/cardstack/backend/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockCatalogService is an autogenerated mock type for the CatalogService type
type MockCatalogService struct {
	mock.Mock
}

type MockCatalogService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogService) EXPECT() *MockCatalogService_Expecter {
	return &MockCatalogService_Expecter{mock: &_m.Mock}
}

// ListCategories provides a mock function with given fields: ctx
func (_m *MockCatalogService) ListCategories(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogService_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type MockCatalogService_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCatalogService_Expecter) ListCategories(ctx interface{}) *MockCatalogService_ListCategories_Call {
	return &MockCatalogService_ListCategories_Call{Call: _e.mock.On("ListCategories", ctx)}
}

func (_c *MockCatalogService_ListCategories_Call) Run(run func(ctx context.Context)) *MockCatalogService_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCatalogService_ListCategories_Call) Return(_a0 []string, _a1 error) *MockCatalogService_ListCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogService_ListCategories_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockCatalogService_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ListFacets provides a mock function with given fields: ctx, filter
func (_m *MockCatalogService) ListFacets(ctx context.Context, filter dto.CardFilter) (dto.CatalogFacets, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListFacets")
	}

	var r0 dto.CatalogFacets
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CardFilter) (dto.CatalogFacets, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CardFilter) dto.CatalogFacets); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(dto.CatalogFacets)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CardFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogService_ListFacets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFacets'
type MockCatalogService_ListFacets_Call struct {
	*mock.Call
}

// ListFacets is a helper method to define mock.On call
//   - ctx context.Context
//   - filter dto.CardFilter
func (_e *MockCatalogService_Expecter) ListFacets(ctx interface{}, filter interface{}) *MockCatalogService_ListFacets_Call {
	return &MockCatalogService_ListFacets_Call{Call: _e.mock.On("ListFacets", ctx, filter)}
}

func (_c *MockCatalogService_ListFacets_Call) Run(run func(ctx context.Context, filter dto.CardFilter)) *MockCatalogService_ListFacets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CardFilter))
	})
	return _c
}

func (_c *MockCatalogService_ListFacets_Call) Return(_a0 dto.CatalogFacets, _a1 error) *MockCatalogService_ListFacets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogService_ListFacets_Call) RunAndReturn(run func(context.Context, dto.CardFilter) (dto.CatalogFacets, error)) *MockCatalogService_ListFacets_Call {
	_c.Call.Return(run)
	return _c
}

// ListRarities provides a mock function with given fields: ctx
func (_m *MockCatalogService) ListRarities(ctx context.Context) ([]dto.RaritySummary, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRarities")
	}

	var r0 []dto.RaritySummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.RaritySummary, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.RaritySummary); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.RaritySummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogService_ListRarities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRarities'
type MockCatalogService_ListRarities_Call struct {
	*mock.Call
}

// ListRarities is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCatalogService_Expecter) ListRarities(ctx interface{}) *MockCatalogService_ListRarities_Call {
	return &MockCatalogService_ListRarities_Call{Call: _e.mock.On("ListRarities", ctx)}
}

func (_c *MockCatalogService_ListRarities_Call) Run(run func(ctx context.Context)) *MockCatalogService_ListRarities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCatalogService_ListRarities_Call) Return(_a0 []dto.RaritySummary, _a1 error) *MockCatalogService_ListRarities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogService_ListRarities_Call) RunAndReturn(run func(context.Context) ([]dto.RaritySummary, error)) *MockCatalogService_ListRarities_Call {
	_c.Call.Return(run)
	return _c
}

// ListSeries provides a mock function with given fields: ctx
func (_m *MockCatalogService) ListSeries(ctx context.Context) (dto.SeriesBrowseResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSeries")
	}

	var r0 dto.SeriesBrowseResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (dto.SeriesBrowseResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) dto.SeriesBrowseResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(dto.SeriesBrowseResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogService_ListSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSeries'
type MockCatalogService_ListSeries_Call struct {
	*mock.Call
}

// ListSeries is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCatalogService_Expecter) ListSeries(ctx interface{}) *MockCatalogService_ListSeries_Call {
	return &MockCatalogService_ListSeries_Call{Call: _e.mock.On("ListSeries", ctx)}
}

func (_c *MockCatalogService_ListSeries_Call) Run(run func(ctx context.Context)) *MockCatalogService_ListSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCatalogService_ListSeries_Call) Return(_a0 dto.SeriesBrowseResult, _a1 error) *MockCatalogService_ListSeries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogService_ListSeries_Call) RunAndReturn(run func(context.Context) (dto.SeriesBrowseResult, error)) *MockCatalogService_ListSeries_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function with given fields: ctx
func (_m *MockCatalogService) ListTags(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogService_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type MockCatalogService_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCatalogService_Expecter) ListTags(ctx interface{}) *MockCatalogService_ListTags_Call {
	return &MockCatalogService_ListTags_Call{Call: _e.mock.On("ListTags", ctx)}
}

func (_c *MockCatalogService_ListTags_Call) Run(run func(ctx context.Context)) *MockCatalogService_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCatalogService_ListTags_Call) Return(_a0 []string, _a1 error) *MockCatalogService_ListTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogService_ListTags_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockCatalogService_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

// SearchCards provides a mock function with given fields: ctx, filter
func (_m *MockCatalogService) SearchCards(ctx context.Context, filter dto.CardFilter) ([]dto.CardSummary, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for SearchCards")
	}

	var r0 []dto.CardSummary
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CardFilter) ([]dto.CardSummary, dto.PaginationMeta, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CardFilter) []dto.CardSummary); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CardSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CardFilter) dto.PaginationMeta); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.CardFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCatalogService_SearchCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchCards'
type MockCatalogService_SearchCards_Call struct {
	*mock.Call
}

// SearchCards is a helper method to define mock.On call
//   - ctx context.Context
//   - filter dto.CardFilter
func (_e *MockCatalogService_Expecter) SearchCards(ctx interface{}, filter interface{}) *MockCatalogService_SearchCards_Call {
	return &MockCatalogService_SearchCards_Call{Call: _e.mock.On("SearchCards", ctx, filter)}
}

func (_c *MockCatalogService_SearchCards_Call) Run(run func(ctx context.Context, filter dto.CardFilter)) *MockCatalogService_SearchCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CardFilter))
	})
	return _c
}

func (_c *MockCatalogService_SearchCards_Call) Return(_a0 []dto.CardSummary, _a1 dto.PaginationMeta, _a2 error) *MockCatalogService_SearchCards_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCatalogService_SearchCards_Call) RunAndReturn(run func(context.Context, dto.CardFilter) ([]dto.CardSummary, dto.PaginationMeta, error)) *MockCatalogService_SearchCards_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCatalogService creates a new instance of MockCatalogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogService {
	mock := &MockCatalogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
