// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/itsLeonB/cardstack/backend/internal/domain/entity"
	crud "github.com/itsLeonB/go-crud"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCollectionRepository is an autogenerated mock type for the CollectionRepository type
type MockCollectionRepository struct {
	mock.Mock
}

type MockCollectionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollectionRepository) EXPECT() *MockCollectionRepository_Expecter {
	return &MockCollectionRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, model
func (_m *MockCollectionRepository) Delete(ctx context.Context, model entity.Collection) error {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Collection) error); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCollectionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCollectionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - model entity.Collection
func (_e *MockCollectionRepository_Expecter) Delete(ctx interface{}, model interface{}) *MockCollectionRepository_Delete_Call {
	return &MockCollectionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, model)}
}

func (_c *MockCollectionRepository_Delete_Call) Run(run func(ctx context.Context, model entity.Collection)) *MockCollectionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Collection))
	})
	return _c
}

func (_c *MockCollectionRepository_Delete_Call) Return(_a0 error) *MockCollectionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCollectionRepository_Delete_Call) RunAndReturn(run func(context.Context, entity.Collection) error) *MockCollectionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function with given fields: ctx, models
func (_m *MockCollectionRepository) DeleteMany(ctx context.Context, models []entity.Collection) error {
	ret := _m.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.Collection) error); ok {
		r0 = rf(ctx, models)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCollectionRepository_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type MockCollectionRepository_DeleteMany_Call struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []entity.Collection
func (_e *MockCollectionRepository_Expecter) DeleteMany(ctx interface{}, models interface{}) *MockCollectionRepository_DeleteMany_Call {
	return &MockCollectionRepository_DeleteMany_Call{Call: _e.mock.On("DeleteMany", ctx, models)}
}

func (_c *MockCollectionRepository_DeleteMany_Call) Run(run func(ctx context.Context, models []entity.Collection)) *MockCollectionRepository_DeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.Collection))
	})
	return _c
}

func (_c *MockCollectionRepository_DeleteMany_Call) Return(_a0 error) *MockCollectionRepository_DeleteMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCollectionRepository_DeleteMany_Call) RunAndReturn(run func(context.Context, []entity.Collection) error) *MockCollectionRepository_DeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, spec
func (_m *MockCollectionRepository) FindAll(ctx context.Context, spec crud.Specification[entity.Collection]) ([]entity.Collection, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Collection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.Collection]) ([]entity.Collection, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.Collection]) []entity.Collection); ok {
		r0 = rf(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Collection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, crud.Specification[entity.Collection]) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockCollectionRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[entity.Collection]
func (_e *MockCollectionRepository_Expecter) FindAll(ctx interface{}, spec interface{}) *MockCollectionRepository_FindAll_Call {
	return &MockCollectionRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, spec)}
}

func (_c *MockCollectionRepository_FindAll_Call) Run(run func(ctx context.Context, spec crud.Specification[entity.Collection])) *MockCollectionRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(crud.Specification[entity.Collection]))
	})
	return _c
}

func (_c *MockCollectionRepository_FindAll_Call) Return(_a0 []entity.Collection, _a1 error) *MockCollectionRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_FindAll_Call) RunAndReturn(run func(context.Context, crud.Specification[entity.Collection]) ([]entity.Collection, error)) *MockCollectionRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindFirst provides a mock function with given fields: ctx, spec
func (_m *MockCollectionRepository) FindFirst(ctx context.Context, spec crud.Specification[entity.Collection]) (entity.Collection, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindFirst")
	}

	var r0 entity.Collection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.Collection]) (entity.Collection, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.Collection]) entity.Collection); ok {
		r0 = rf(ctx, spec)
	} else {
		r0 = ret.Get(0).(entity.Collection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, crud.Specification[entity.Collection]) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionRepository_FindFirst_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFirst'
type MockCollectionRepository_FindFirst_Call struct {
	*mock.Call
}

// FindFirst is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[entity.Collection]
func (_e *MockCollectionRepository_Expecter) FindFirst(ctx interface{}, spec interface{}) *MockCollectionRepository_FindFirst_Call {
	return &MockCollectionRepository_FindFirst_Call{Call: _e.mock.On("FindFirst", ctx, spec)}
}

func (_c *MockCollectionRepository_FindFirst_Call) Run(run func(ctx context.Context, spec crud.Specification[entity.Collection])) *MockCollectionRepository_FindFirst_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(crud.Specification[entity.Collection]))
	})
	return _c
}

func (_c *MockCollectionRepository_FindFirst_Call) Return(_a0 entity.Collection, _a1 error) *MockCollectionRepository_FindFirst_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_FindFirst_Call) RunAndReturn(run func(context.Context, crud.Specification[entity.Collection]) (entity.Collection, error)) *MockCollectionRepository_FindFirst_Call {
	_c.Call.Return(run)
	return _c
}

// GetGormInstance provides a mock function with given fields: ctx
func (_m *MockCollectionRepository) GetGormInstance(ctx context.Context) (*gorm.DB, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGormInstance")
	}

	var r0 *gorm.DB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionRepository_GetGormInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGormInstance'
type MockCollectionRepository_GetGormInstance_Call struct {
	*mock.Call
}

// GetGormInstance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCollectionRepository_Expecter) GetGormInstance(ctx interface{}) *MockCollectionRepository_GetGormInstance_Call {
	return &MockCollectionRepository_GetGormInstance_Call{Call: _e.mock.On("GetGormInstance", ctx)}
}

func (_c *MockCollectionRepository_GetGormInstance_Call) Run(run func(ctx context.Context)) *MockCollectionRepository_GetGormInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCollectionRepository_GetGormInstance_Call) Return(_a0 *gorm.DB, _a1 error) *MockCollectionRepository_GetGormInstance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_GetGormInstance_Call) RunAndReturn(run func(context.Context) (*gorm.DB, error)) *MockCollectionRepository_GetGormInstance_Call {
	_c.Call.Return(run)
	return _c
}

// GetOwnedCollection provides a mock function with given fields: ctx, profileID, collectionID, forUpdate
func (_m *MockCollectionRepository) GetOwnedCollection(ctx context.Context, profileID uuid.UUID, collectionID uuid.UUID, forUpdate bool) (entity.Collection, error) {
	ret := _m.Called(ctx, profileID, collectionID, forUpdate)

	if len(ret) == 0 {
		panic("no return value specified for GetOwnedCollection")
	}

	var r0 entity.Collection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) (entity.Collection, error)); ok {
		return rf(ctx, profileID, collectionID, forUpdate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) entity.Collection); ok {
		r0 = rf(ctx, profileID, collectionID, forUpdate)
	} else {
		r0 = ret.Get(0).(entity.Collection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, profileID, collectionID, forUpdate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionRepository_GetOwnedCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOwnedCollection'
type MockCollectionRepository_GetOwnedCollection_Call struct {
	*mock.Call
}

// GetOwnedCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uuid.UUID
//   - collectionID uuid.UUID
//   - forUpdate bool
func (_e *MockCollectionRepository_Expecter) GetOwnedCollection(ctx interface{}, profileID interface{}, collectionID interface{}, forUpdate interface{}) *MockCollectionRepository_GetOwnedCollection_Call {
	return &MockCollectionRepository_GetOwnedCollection_Call{Call: _e.mock.On("GetOwnedCollection", ctx, profileID, collectionID, forUpdate)}
}

func (_c *MockCollectionRepository_GetOwnedCollection_Call) Run(run func(ctx context.Context, profileID uuid.UUID, collectionID uuid.UUID, forUpdate bool)) *MockCollectionRepository_GetOwnedCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(bool))
	})
	return _c
}

func (_c *MockCollectionRepository_GetOwnedCollection_Call) Return(_a0 entity.Collection, _a1 error) *MockCollectionRepository_GetOwnedCollection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_GetOwnedCollection_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, bool) (entity.Collection, error)) *MockCollectionRepository_GetOwnedCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, model
func (_m *MockCollectionRepository) Insert(ctx context.Context, model entity.Collection) (entity.Collection, error) {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 entity.Collection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Collection) (entity.Collection, error)); ok {
		return rf(ctx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Collection) entity.Collection); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Get(0).(entity.Collection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Collection) error); ok {
		r1 = rf(ctx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockCollectionRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - model entity.Collection
func (_e *MockCollectionRepository_Expecter) Insert(ctx interface{}, model interface{}) *MockCollectionRepository_Insert_Call {
	return &MockCollectionRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, model)}
}

func (_c *MockCollectionRepository_Insert_Call) Run(run func(ctx context.Context, model entity.Collection)) *MockCollectionRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Collection))
	})
	return _c
}

func (_c *MockCollectionRepository_Insert_Call) Return(_a0 entity.Collection, _a1 error) *MockCollectionRepository_Insert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_Insert_Call) RunAndReturn(run func(context.Context, entity.Collection) (entity.Collection, error)) *MockCollectionRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function with given fields: ctx, models
func (_m *MockCollectionRepository) InsertMany(ctx context.Context, models []entity.Collection) ([]entity.Collection, error) {
	ret := _m.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 []entity.Collection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.Collection) ([]entity.Collection, error)); ok {
		return rf(ctx, models)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []entity.Collection) []entity.Collection); ok {
		r0 = rf(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Collection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []entity.Collection) error); ok {
		r1 = rf(ctx, models)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionRepository_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockCollectionRepository_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []entity.Collection
func (_e *MockCollectionRepository_Expecter) InsertMany(ctx interface{}, models interface{}) *MockCollectionRepository_InsertMany_Call {
	return &MockCollectionRepository_InsertMany_Call{Call: _e.mock.On("InsertMany", ctx, models)}
}

func (_c *MockCollectionRepository_InsertMany_Call) Run(run func(ctx context.Context, models []entity.Collection)) *MockCollectionRepository_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.Collection))
	})
	return _c
}

func (_c *MockCollectionRepository_InsertMany_Call) Return(_a0 []entity.Collection, _a1 error) *MockCollectionRepository_InsertMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_InsertMany_Call) RunAndReturn(run func(context.Context, []entity.Collection) ([]entity.Collection, error)) *MockCollectionRepository_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMany provides a mock function with given fields: ctx, models
func (_m *MockCollectionRepository) SaveMany(ctx context.Context, models []entity.Collection) ([]entity.Collection, error) {
	ret := _m.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 []entity.Collection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.Collection) ([]entity.Collection, error)); ok {
		return rf(ctx, models)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []entity.Collection) []entity.Collection); ok {
		r0 = rf(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Collection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []entity.Collection) error); ok {
		r1 = rf(ctx, models)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionRepository_SaveMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMany'
type MockCollectionRepository_SaveMany_Call struct {
	*mock.Call
}

// SaveMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []entity.Collection
func (_e *MockCollectionRepository_Expecter) SaveMany(ctx interface{}, models interface{}) *MockCollectionRepository_SaveMany_Call {
	return &MockCollectionRepository_SaveMany_Call{Call: _e.mock.On("SaveMany", ctx, models)}
}

func (_c *MockCollectionRepository_SaveMany_Call) Run(run func(ctx context.Context, models []entity.Collection)) *MockCollectionRepository_SaveMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.Collection))
	})
	return _c
}

func (_c *MockCollectionRepository_SaveMany_Call) Return(_a0 []entity.Collection, _a1 error) *MockCollectionRepository_SaveMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_SaveMany_Call) RunAndReturn(run func(context.Context, []entity.Collection) ([]entity.Collection, error)) *MockCollectionRepository_SaveMany_Call {
	_c.Call.Return(run)
	return _c
}

// SumQuantities provides a mock function with given fields: ctx, collectionIDs
func (_m *MockCollectionRepository) SumQuantities(ctx context.Context, collectionIDs []uuid.UUID) (map[uuid.UUID]int, error) {
	ret := _m.Called(ctx, collectionIDs)

	if len(ret) == 0 {
		panic("no return value specified for SumQuantities")
	}

	var r0 map[uuid.UUID]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID]int, error)); ok {
		return rf(ctx, collectionIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID]int); ok {
		r0 = rf(ctx, collectionIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, collectionIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionRepository_SumQuantities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumQuantities'
type MockCollectionRepository_SumQuantities_Call struct {
	*mock.Call
}

// SumQuantities is a helper method to define mock.On call
//   - ctx context.Context
//   - collectionIDs []uuid.UUID
func (_e *MockCollectionRepository_Expecter) SumQuantities(ctx interface{}, collectionIDs interface{}) *MockCollectionRepository_SumQuantities_Call {
	return &MockCollectionRepository_SumQuantities_Call{Call: _e.mock.On("SumQuantities", ctx, collectionIDs)}
}

func (_c *MockCollectionRepository_SumQuantities_Call) Run(run func(ctx context.Context, collectionIDs []uuid.UUID)) *MockCollectionRepository_SumQuantities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockCollectionRepository_SumQuantities_Call) Return(_a0 map[uuid.UUID]int, _a1 error) *MockCollectionRepository_SumQuantities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_SumQuantities_Call) RunAndReturn(run func(context.Context, []uuid.UUID) (map[uuid.UUID]int, error)) *MockCollectionRepository_SumQuantities_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, model
func (_m *MockCollectionRepository) Update(ctx context.Context, model entity.Collection) (entity.Collection, error) {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.Collection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Collection) (entity.Collection, error)); ok {
		return rf(ctx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Collection) entity.Collection); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Get(0).(entity.Collection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Collection) error); ok {
		r1 = rf(ctx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCollectionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - model entity.Collection
func (_e *MockCollectionRepository_Expecter) Update(ctx interface{}, model interface{}) *MockCollectionRepository_Update_Call {
	return &MockCollectionRepository_Update_Call{Call: _e.mock.On("Update", ctx, model)}
}

func (_c *MockCollectionRepository_Update_Call) Run(run func(ctx context.Context, model entity.Collection)) *MockCollectionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Collection))
	})
	return _c
}

func (_c *MockCollectionRepository_Update_Call) Return(_a0 entity.Collection, _a1 error) *MockCollectionRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_Update_Call) RunAndReturn(run func(context.Context, entity.Collection) (entity.Collection, error)) *MockCollectionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCollectionRepository creates a new instance of MockCollectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollectionRepository {
	mock := &MockCollectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
