// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/itsLeonB/cardstack/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCollectionRepository is an autogenerated mock type for the CollectionRepository type
type MockCollectionRepository struct {
	mock.Mock
}

type MockCollectionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollectionRepository) EXPECT() *MockCollectionRepository_Expecter {
	return &MockCollectionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, c
func (_m *MockCollectionRepository) Create(ctx context.Context, c entity.Collection) (entity.Collection, error) {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Collection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Collection) (entity.Collection, error)); ok {
		return rf(ctx, c)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Collection) entity.Collection); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Get(0).(entity.Collection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Collection) error); ok {
		r1 = rf(ctx, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCollectionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - c entity.Collection
func (_e *MockCollectionRepository_Expecter) Create(ctx interface{}, c interface{}) *MockCollectionRepository_Create_Call {
	return &MockCollectionRepository_Create_Call{Call: _e.mock.On("Create", ctx, c)}
}

func (_c *MockCollectionRepository_Create_Call) Run(run func(ctx context.Context, c entity.Collection)) *MockCollectionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Collection))
	})
	return _c
}

func (_c *MockCollectionRepository_Create_Call) Return(_a0 entity.Collection, _a1 error) *MockCollectionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_Create_Call) RunAndReturn(run func(context.Context, entity.Collection) (entity.Collection, error)) *MockCollectionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, c
func (_m *MockCollectionRepository) Delete(ctx context.Context, c entity.Collection) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Collection) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCollectionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCollectionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - c entity.Collection
func (_e *MockCollectionRepository_Expecter) Delete(ctx interface{}, c interface{}) *MockCollectionRepository_Delete_Call {
	return &MockCollectionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, c)}
}

func (_c *MockCollectionRepository_Delete_Call) Run(run func(ctx context.Context, c entity.Collection)) *MockCollectionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Collection))
	})
	return _c
}

func (_c *MockCollectionRepository_Delete_Call) Return(_a0 error) *MockCollectionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCollectionRepository_Delete_Call) RunAndReturn(run func(context.Context, entity.Collection) error) *MockCollectionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCollectionRepository) FindByID(ctx context.Context, id uuid.UUID) (entity.Collection, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entity.Collection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Collection, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Collection); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Collection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCollectionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCollectionRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockCollectionRepository_FindByID_Call {
	return &MockCollectionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCollectionRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCollectionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCollectionRepository_FindByID_Call) Return(_a0 entity.Collection, _a1 error) *MockCollectionRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Collection, error)) *MockCollectionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *MockCollectionRepository) ListByUser(ctx context.Context, userID uuid.UUID) ([]entity.Collection, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []entity.Collection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Collection, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Collection); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Collection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockCollectionRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCollectionRepository_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockCollectionRepository_ListByUser_Call {
	return &MockCollectionRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockCollectionRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCollectionRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCollectionRepository_ListByUser_Call) Return(_a0 []entity.Collection, _a1 error) *MockCollectionRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_ListByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.Collection, error)) *MockCollectionRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, c
func (_m *MockCollectionRepository) Update(ctx context.Context, c entity.Collection) (entity.Collection, error) {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.Collection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Collection) (entity.Collection, error)); ok {
		return rf(ctx, c)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Collection) entity.Collection); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Get(0).(entity.Collection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Collection) error); ok {
		r1 = rf(ctx, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCollectionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - c entity.Collection
func (_e *MockCollectionRepository_Expecter) Update(ctx interface{}, c interface{}) *MockCollectionRepository_Update_Call {
	return &MockCollectionRepository_Update_Call{Call: _e.mock.On("Update", ctx, c)}
}

func (_c *MockCollectionRepository_Update_Call) Run(run func(ctx context.Context, c entity.Collection)) *MockCollectionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Collection))
	})
	return _c
}

func (_c *MockCollectionRepository_Update_Call) Return(_a0 entity.Collection, _a1 error) *MockCollectionRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_Update_Call) RunAndReturn(run func(context.Context, entity.Collection) (entity.Collection, error)) *MockCollectionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCollectionRepository creates a new instance of MockCollectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollectionRepository {
	mock := &MockCollectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
