// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/itsLeonB/cardstack/backend/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockCollectionService is an autogenerated mock type for the CollectionService type
type MockCollectionService struct {
	mock.Mock
}

type MockCollectionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollectionService) EXPECT() *MockCollectionService_Expecter {
	return &MockCollectionService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockCollectionService) Create(ctx context.Context, req dto.CollectionRequest) (dto.CollectionSummary, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 dto.CollectionSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CollectionRequest) (dto.CollectionSummary, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CollectionRequest) dto.CollectionSummary); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.CollectionSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CollectionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCollectionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CollectionRequest
func (_e *MockCollectionService_Expecter) Create(ctx interface{}, req interface{}) *MockCollectionService_Create_Call {
	return &MockCollectionService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockCollectionService_Create_Call) Run(run func(ctx context.Context, req dto.CollectionRequest)) *MockCollectionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CollectionRequest))
	})
	return _c
}

func (_c *MockCollectionService_Create_Call) Return(_a0 dto.CollectionSummary, _a1 error) *MockCollectionService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionService_Create_Call) RunAndReturn(run func(context.Context, dto.CollectionRequest) (dto.CollectionSummary, error)) *MockCollectionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, req
func (_m *MockCollectionService) Delete(ctx context.Context, req dto.CollectionLookup) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CollectionLookup) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCollectionService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCollectionService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CollectionLookup
func (_e *MockCollectionService_Expecter) Delete(ctx interface{}, req interface{}) *MockCollectionService_Delete_Call {
	return &MockCollectionService_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *MockCollectionService_Delete_Call) Run(run func(ctx context.Context, req dto.CollectionLookup)) *MockCollectionService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CollectionLookup))
	})
	return _c
}

func (_c *MockCollectionService_Delete_Call) Return(_a0 error) *MockCollectionService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCollectionService_Delete_Call) RunAndReturn(run func(context.Context, dto.CollectionLookup) error) *MockCollectionService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, req
func (_m *MockCollectionService) Get(ctx context.Context, req dto.CollectionLookup) (dto.CollectionSummary, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 dto.CollectionSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CollectionLookup) (dto.CollectionSummary, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CollectionLookup) dto.CollectionSummary); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.CollectionSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CollectionLookup) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCollectionService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CollectionLookup
func (_e *MockCollectionService_Expecter) Get(ctx interface{}, req interface{}) *MockCollectionService_Get_Call {
	return &MockCollectionService_Get_Call{Call: _e.mock.On("Get", ctx, req)}
}

func (_c *MockCollectionService_Get_Call) Run(run func(ctx context.Context, req dto.CollectionLookup)) *MockCollectionService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CollectionLookup))
	})
	return _c
}

func (_c *MockCollectionService_Get_Call) Return(_a0 dto.CollectionSummary, _a1 error) *MockCollectionService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionService_Get_Call) RunAndReturn(run func(context.Context, dto.CollectionLookup) (dto.CollectionSummary, error)) *MockCollectionService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, req
func (_m *MockCollectionService) List(ctx context.Context, req dto.CollectionListRequest) ([]dto.CollectionSummary, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []dto.CollectionSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CollectionListRequest) ([]dto.CollectionSummary, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CollectionListRequest) []dto.CollectionSummary); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CollectionSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CollectionListRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCollectionService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CollectionListRequest
func (_e *MockCollectionService_Expecter) List(ctx interface{}, req interface{}) *MockCollectionService_List_Call {
	return &MockCollectionService_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *MockCollectionService_List_Call) Run(run func(ctx context.Context, req dto.CollectionListRequest)) *MockCollectionService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CollectionListRequest))
	})
	return _c
}

func (_c *MockCollectionService_List_Call) Return(_a0 []dto.CollectionSummary, _a1 error) *MockCollectionService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionService_List_Call) RunAndReturn(run func(context.Context, dto.CollectionListRequest) ([]dto.CollectionSummary, error)) *MockCollectionService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, req
func (_m *MockCollectionService) Update(ctx context.Context, req dto.CollectionRequest) (dto.CollectionSummary, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.CollectionSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CollectionRequest) (dto.CollectionSummary, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CollectionRequest) dto.CollectionSummary); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.CollectionSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CollectionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollectionService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCollectionService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CollectionRequest
func (_e *MockCollectionService_Expecter) Update(ctx interface{}, req interface{}) *MockCollectionService_Update_Call {
	return &MockCollectionService_Update_Call{Call: _e.mock.On("Update", ctx, req)}
}

func (_c *MockCollectionService_Update_Call) Run(run func(ctx context.Context, req dto.CollectionRequest)) *MockCollectionService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CollectionRequest))
	})
	return _c
}

func (_c *MockCollectionService_Update_Call) Return(_a0 dto.CollectionSummary, _a1 error) *MockCollectionService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionService_Update_Call) RunAndReturn(run func(context.Context, dto.CollectionRequest) (dto.CollectionSummary, error)) *MockCollectionService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCollectionService creates a new instance of MockCollectionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollectionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollectionService {
	mock := &MockCollectionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
