// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/itsLeonB/cardstack/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/itsLeonB/cardstack/backend/internal/domain/repository"
)

// MockEmbeddingRepository is an autogenerated mock type for the EmbeddingRepository type
type MockEmbeddingRepository struct {
	mock.Mock
}

type MockEmbeddingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingRepository) EXPECT() *MockEmbeddingRepository_Expecter {
	return &MockEmbeddingRepository_Expecter{mock: &_m.Mock}
}

// CountEmbeddingStates provides a mock function with given fields: ctx, model, setCode
func (_m *MockEmbeddingRepository) CountEmbeddingStates(ctx context.Context, model string, setCode string) (repository.EmbeddingStates, error) {
	ret := _m.Called(ctx, model, setCode)

	if len(ret) == 0 {
		panic("no return value specified for CountEmbeddingStates")
	}

	var r0 repository.EmbeddingStates
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (repository.EmbeddingStates, error)); ok {
		return rf(ctx, model, setCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) repository.EmbeddingStates); ok {
		r0 = rf(ctx, model, setCode)
	} else {
		r0 = ret.Get(0).(repository.EmbeddingStates)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, model, setCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmbeddingRepository_CountEmbeddingStates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountEmbeddingStates'
type MockEmbeddingRepository_CountEmbeddingStates_Call struct {
	*mock.Call
}

// CountEmbeddingStates is a helper method to define mock.On call
//   - ctx context.Context
//   - model string
//   - setCode string
func (_e *MockEmbeddingRepository_Expecter) CountEmbeddingStates(ctx interface{}, model interface{}, setCode interface{}) *MockEmbeddingRepository_CountEmbeddingStates_Call {
	return &MockEmbeddingRepository_CountEmbeddingStates_Call{Call: _e.mock.On("CountEmbeddingStates", ctx, model, setCode)}
}

func (_c *MockEmbeddingRepository_CountEmbeddingStates_Call) Run(run func(ctx context.Context, model string, setCode string)) *MockEmbeddingRepository_CountEmbeddingStates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockEmbeddingRepository_CountEmbeddingStates_Call) Return(_a0 repository.EmbeddingStates, _a1 error) *MockEmbeddingRepository_CountEmbeddingStates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmbeddingRepository_CountEmbeddingStates_Call) RunAndReturn(run func(context.Context, string, string) (repository.EmbeddingStates, error)) *MockEmbeddingRepository_CountEmbeddingStates_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingCards provides a mock function with given fields: ctx, model, setCode
func (_m *MockEmbeddingRepository) ListPendingCards(ctx context.Context, model string, setCode string) ([]entity.Card, error) {
	ret := _m.Called(ctx, model, setCode)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingCards")
	}

	var r0 []entity.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]entity.Card, error)); ok {
		return rf(ctx, model, setCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []entity.Card); ok {
		r0 = rf(ctx, model, setCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, model, setCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmbeddingRepository_ListPendingCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingCards'
type MockEmbeddingRepository_ListPendingCards_Call struct {
	*mock.Call
}

// ListPendingCards is a helper method to define mock.On call
//   - ctx context.Context
//   - model string
//   - setCode string
func (_e *MockEmbeddingRepository_Expecter) ListPendingCards(ctx interface{}, model interface{}, setCode interface{}) *MockEmbeddingRepository_ListPendingCards_Call {
	return &MockEmbeddingRepository_ListPendingCards_Call{Call: _e.mock.On("ListPendingCards", ctx, model, setCode)}
}

func (_c *MockEmbeddingRepository_ListPendingCards_Call) Run(run func(ctx context.Context, model string, setCode string)) *MockEmbeddingRepository_ListPendingCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockEmbeddingRepository_ListPendingCards_Call) Return(_a0 []entity.Card, _a1 error) *MockEmbeddingRepository_ListPendingCards_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmbeddingRepository_ListPendingCards_Call) RunAndReturn(run func(context.Context, string, string) ([]entity.Card, error)) *MockEmbeddingRepository_ListPendingCards_Call {
	_c.Call.Return(run)
	return _c
}

// NearestCards provides a mock function with given fields: ctx, model, query, limit
func (_m *MockEmbeddingRepository) NearestCards(ctx context.Context, model string, query []float32, limit int) ([]repository.CardDistance, error) {
	ret := _m.Called(ctx, model, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for NearestCards")
	}

	var r0 []repository.CardDistance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []float32, int) ([]repository.CardDistance, error)); ok {
		return rf(ctx, model, query, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []float32, int) []repository.CardDistance); ok {
		r0 = rf(ctx, model, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.CardDistance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []float32, int) error); ok {
		r1 = rf(ctx, model, query, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmbeddingRepository_NearestCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NearestCards'
type MockEmbeddingRepository_NearestCards_Call struct {
	*mock.Call
}

// NearestCards is a helper method to define mock.On call
//   - ctx context.Context
//   - model string
//   - query []float32
//   - limit int
func (_e *MockEmbeddingRepository_Expecter) NearestCards(ctx interface{}, model interface{}, query interface{}, limit interface{}) *MockEmbeddingRepository_NearestCards_Call {
	return &MockEmbeddingRepository_NearestCards_Call{Call: _e.mock.On("NearestCards", ctx, model, query, limit)}
}

func (_c *MockEmbeddingRepository_NearestCards_Call) Run(run func(ctx context.Context, model string, query []float32, limit int)) *MockEmbeddingRepository_NearestCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]float32), args[3].(int))
	})
	return _c
}

func (_c *MockEmbeddingRepository_NearestCards_Call) Return(_a0 []repository.CardDistance, _a1 error) *MockEmbeddingRepository_NearestCards_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmbeddingRepository_NearestCards_Call) RunAndReturn(run func(context.Context, string, []float32, int) ([]repository.CardDistance, error)) *MockEmbeddingRepository_NearestCards_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, e
func (_m *MockEmbeddingRepository) Upsert(ctx context.Context, e entity.CardEmbedding) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CardEmbedding) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmbeddingRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockEmbeddingRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - e entity.CardEmbedding
func (_e *MockEmbeddingRepository_Expecter) Upsert(ctx interface{}, e interface{}) *MockEmbeddingRepository_Upsert_Call {
	return &MockEmbeddingRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, e)}
}

func (_c *MockEmbeddingRepository_Upsert_Call) Run(run func(ctx context.Context, e entity.CardEmbedding)) *MockEmbeddingRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CardEmbedding))
	})
	return _c
}

func (_c *MockEmbeddingRepository_Upsert_Call) Return(_a0 error) *MockEmbeddingRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmbeddingRepository_Upsert_Call) RunAndReturn(run func(context.Context, entity.CardEmbedding) error) *MockEmbeddingRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmbeddingRepository creates a new instance of MockEmbeddingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingRepository {
	mock := &MockEmbeddingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
