// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/itsLeonB/cardstack/backend/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockEmbeddingService is an autogenerated mock type for the EmbeddingService type
type MockEmbeddingService struct {
	mock.Mock
}

type MockEmbeddingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingService) EXPECT() *MockEmbeddingService_Expecter {
	return &MockEmbeddingService_Expecter{mock: &_m.Mock}
}

// EmbedCatalog provides a mock function with given fields: ctx, req
func (_m *MockEmbeddingService) EmbedCatalog(ctx context.Context, req dto.EmbedCatalogRequest) (dto.EmbedCatalogSummary, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EmbedCatalog")
	}

	var r0 dto.EmbedCatalogSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.EmbedCatalogRequest) (dto.EmbedCatalogSummary, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.EmbedCatalogRequest) dto.EmbedCatalogSummary); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.EmbedCatalogSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.EmbedCatalogRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmbeddingService_EmbedCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmbedCatalog'
type MockEmbeddingService_EmbedCatalog_Call struct {
	*mock.Call
}

// EmbedCatalog is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.EmbedCatalogRequest
func (_e *MockEmbeddingService_Expecter) EmbedCatalog(ctx interface{}, req interface{}) *MockEmbeddingService_EmbedCatalog_Call {
	return &MockEmbeddingService_EmbedCatalog_Call{Call: _e.mock.On("EmbedCatalog", ctx, req)}
}

func (_c *MockEmbeddingService_EmbedCatalog_Call) Run(run func(ctx context.Context, req dto.EmbedCatalogRequest)) *MockEmbeddingService_EmbedCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.EmbedCatalogRequest))
	})
	return _c
}

func (_c *MockEmbeddingService_EmbedCatalog_Call) Return(_a0 dto.EmbedCatalogSummary, _a1 error) *MockEmbeddingService_EmbedCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmbeddingService_EmbedCatalog_Call) RunAndReturn(run func(context.Context, dto.EmbedCatalogRequest) (dto.EmbedCatalogSummary, error)) *MockEmbeddingService_EmbedCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmbeddingService creates a new instance of MockEmbeddingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingService {
	mock := &MockEmbeddingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
