// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/itsLeonB/cardstack/backend/internal/domain/entity"
	crud "github.com/itsLeonB/go-crud"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// MockExpansionSetRepository is an autogenerated mock type for the ExpansionSetRepository type
type MockExpansionSetRepository struct {
	mock.Mock
}

type MockExpansionSetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpansionSetRepository) EXPECT() *MockExpansionSetRepository_Expecter {
	return &MockExpansionSetRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, model
func (_m *MockExpansionSetRepository) Delete(ctx context.Context, model entity.ExpansionSet) error {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ExpansionSet) error); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpansionSetRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockExpansionSetRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - model entity.ExpansionSet
func (_e *MockExpansionSetRepository_Expecter) Delete(ctx interface{}, model interface{}) *MockExpansionSetRepository_Delete_Call {
	return &MockExpansionSetRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, model)}
}

func (_c *MockExpansionSetRepository_Delete_Call) Run(run func(ctx context.Context, model entity.ExpansionSet)) *MockExpansionSetRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ExpansionSet))
	})
	return _c
}

func (_c *MockExpansionSetRepository_Delete_Call) Return(_a0 error) *MockExpansionSetRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpansionSetRepository_Delete_Call) RunAndReturn(run func(context.Context, entity.ExpansionSet) error) *MockExpansionSetRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function with given fields: ctx, models
func (_m *MockExpansionSetRepository) DeleteMany(ctx context.Context, models []entity.ExpansionSet) error {
	ret := _m.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.ExpansionSet) error); ok {
		r0 = rf(ctx, models)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpansionSetRepository_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type MockExpansionSetRepository_DeleteMany_Call struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []entity.ExpansionSet
func (_e *MockExpansionSetRepository_Expecter) DeleteMany(ctx interface{}, models interface{}) *MockExpansionSetRepository_DeleteMany_Call {
	return &MockExpansionSetRepository_DeleteMany_Call{Call: _e.mock.On("DeleteMany", ctx, models)}
}

func (_c *MockExpansionSetRepository_DeleteMany_Call) Run(run func(ctx context.Context, models []entity.ExpansionSet)) *MockExpansionSetRepository_DeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.ExpansionSet))
	})
	return _c
}

func (_c *MockExpansionSetRepository_DeleteMany_Call) Return(_a0 error) *MockExpansionSetRepository_DeleteMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpansionSetRepository_DeleteMany_Call) RunAndReturn(run func(context.Context, []entity.ExpansionSet) error) *MockExpansionSetRepository_DeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, spec
func (_m *MockExpansionSetRepository) FindAll(ctx context.Context, spec crud.Specification[entity.ExpansionSet]) ([]entity.ExpansionSet, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.ExpansionSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.ExpansionSet]) ([]entity.ExpansionSet, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.ExpansionSet]) []entity.ExpansionSet); ok {
		r0 = rf(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ExpansionSet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, crud.Specification[entity.ExpansionSet]) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpansionSetRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockExpansionSetRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[entity.ExpansionSet]
func (_e *MockExpansionSetRepository_Expecter) FindAll(ctx interface{}, spec interface{}) *MockExpansionSetRepository_FindAll_Call {
	return &MockExpansionSetRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, spec)}
}

func (_c *MockExpansionSetRepository_FindAll_Call) Run(run func(ctx context.Context, spec crud.Specification[entity.ExpansionSet])) *MockExpansionSetRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(crud.Specification[entity.ExpansionSet]))
	})
	return _c
}

func (_c *MockExpansionSetRepository_FindAll_Call) Return(_a0 []entity.ExpansionSet, _a1 error) *MockExpansionSetRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpansionSetRepository_FindAll_Call) RunAndReturn(run func(context.Context, crud.Specification[entity.ExpansionSet]) ([]entity.ExpansionSet, error)) *MockExpansionSetRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindFirst provides a mock function with given fields: ctx, spec
func (_m *MockExpansionSetRepository) FindFirst(ctx context.Context, spec crud.Specification[entity.ExpansionSet]) (entity.ExpansionSet, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindFirst")
	}

	var r0 entity.ExpansionSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.ExpansionSet]) (entity.ExpansionSet, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.ExpansionSet]) entity.ExpansionSet); ok {
		r0 = rf(ctx, spec)
	} else {
		r0 = ret.Get(0).(entity.ExpansionSet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, crud.Specification[entity.ExpansionSet]) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpansionSetRepository_FindFirst_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFirst'
type MockExpansionSetRepository_FindFirst_Call struct {
	*mock.Call
}

// FindFirst is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[entity.ExpansionSet]
func (_e *MockExpansionSetRepository_Expecter) FindFirst(ctx interface{}, spec interface{}) *MockExpansionSetRepository_FindFirst_Call {
	return &MockExpansionSetRepository_FindFirst_Call{Call: _e.mock.On("FindFirst", ctx, spec)}
}

func (_c *MockExpansionSetRepository_FindFirst_Call) Run(run func(ctx context.Context, spec crud.Specification[entity.ExpansionSet])) *MockExpansionSetRepository_FindFirst_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(crud.Specification[entity.ExpansionSet]))
	})
	return _c
}

func (_c *MockExpansionSetRepository_FindFirst_Call) Return(_a0 entity.ExpansionSet, _a1 error) *MockExpansionSetRepository_FindFirst_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpansionSetRepository_FindFirst_Call) RunAndReturn(run func(context.Context, crud.Specification[entity.ExpansionSet]) (entity.ExpansionSet, error)) *MockExpansionSetRepository_FindFirst_Call {
	_c.Call.Return(run)
	return _c
}

// GetGormInstance provides a mock function with given fields: ctx
func (_m *MockExpansionSetRepository) GetGormInstance(ctx context.Context) (*gorm.DB, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGormInstance")
	}

	var r0 *gorm.DB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpansionSetRepository_GetGormInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGormInstance'
type MockExpansionSetRepository_GetGormInstance_Call struct {
	*mock.Call
}

// GetGormInstance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockExpansionSetRepository_Expecter) GetGormInstance(ctx interface{}) *MockExpansionSetRepository_GetGormInstance_Call {
	return &MockExpansionSetRepository_GetGormInstance_Call{Call: _e.mock.On("GetGormInstance", ctx)}
}

func (_c *MockExpansionSetRepository_GetGormInstance_Call) Run(run func(ctx context.Context)) *MockExpansionSetRepository_GetGormInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockExpansionSetRepository_GetGormInstance_Call) Return(_a0 *gorm.DB, _a1 error) *MockExpansionSetRepository_GetGormInstance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpansionSetRepository_GetGormInstance_Call) RunAndReturn(run func(context.Context) (*gorm.DB, error)) *MockExpansionSetRepository_GetGormInstance_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, model
func (_m *MockExpansionSetRepository) Insert(ctx context.Context, model entity.ExpansionSet) (entity.ExpansionSet, error) {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 entity.ExpansionSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ExpansionSet) (entity.ExpansionSet, error)); ok {
		return rf(ctx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ExpansionSet) entity.ExpansionSet); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Get(0).(entity.ExpansionSet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ExpansionSet) error); ok {
		r1 = rf(ctx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpansionSetRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockExpansionSetRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - model entity.ExpansionSet
func (_e *MockExpansionSetRepository_Expecter) Insert(ctx interface{}, model interface{}) *MockExpansionSetRepository_Insert_Call {
	return &MockExpansionSetRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, model)}
}

func (_c *MockExpansionSetRepository_Insert_Call) Run(run func(ctx context.Context, model entity.ExpansionSet)) *MockExpansionSetRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ExpansionSet))
	})
	return _c
}

func (_c *MockExpansionSetRepository_Insert_Call) Return(_a0 entity.ExpansionSet, _a1 error) *MockExpansionSetRepository_Insert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpansionSetRepository_Insert_Call) RunAndReturn(run func(context.Context, entity.ExpansionSet) (entity.ExpansionSet, error)) *MockExpansionSetRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function with given fields: ctx, models
func (_m *MockExpansionSetRepository) InsertMany(ctx context.Context, models []entity.ExpansionSet) ([]entity.ExpansionSet, error) {
	ret := _m.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 []entity.ExpansionSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.ExpansionSet) ([]entity.ExpansionSet, error)); ok {
		return rf(ctx, models)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []entity.ExpansionSet) []entity.ExpansionSet); ok {
		r0 = rf(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ExpansionSet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []entity.ExpansionSet) error); ok {
		r1 = rf(ctx, models)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpansionSetRepository_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockExpansionSetRepository_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []entity.ExpansionSet
func (_e *MockExpansionSetRepository_Expecter) InsertMany(ctx interface{}, models interface{}) *MockExpansionSetRepository_InsertMany_Call {
	return &MockExpansionSetRepository_InsertMany_Call{Call: _e.mock.On("InsertMany", ctx, models)}
}

func (_c *MockExpansionSetRepository_InsertMany_Call) Run(run func(ctx context.Context, models []entity.ExpansionSet)) *MockExpansionSetRepository_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.ExpansionSet))
	})
	return _c
}

func (_c *MockExpansionSetRepository_InsertMany_Call) Return(_a0 []entity.ExpansionSet, _a1 error) *MockExpansionSetRepository_InsertMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpansionSetRepository_InsertMany_Call) RunAndReturn(run func(context.Context, []entity.ExpansionSet) ([]entity.ExpansionSet, error)) *MockExpansionSetRepository_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// ListMissingCovers provides a mock function with given fields: ctx, code
func (_m *MockExpansionSetRepository) ListMissingCovers(ctx context.Context, code string) ([]entity.ExpansionSet, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for ListMissingCovers")
	}

	var r0 []entity.ExpansionSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.ExpansionSet, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.ExpansionSet); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ExpansionSet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpansionSetRepository_ListMissingCovers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMissingCovers'
type MockExpansionSetRepository_ListMissingCovers_Call struct {
	*mock.Call
}

// ListMissingCovers is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockExpansionSetRepository_Expecter) ListMissingCovers(ctx interface{}, code interface{}) *MockExpansionSetRepository_ListMissingCovers_Call {
	return &MockExpansionSetRepository_ListMissingCovers_Call{Call: _e.mock.On("ListMissingCovers", ctx, code)}
}

func (_c *MockExpansionSetRepository_ListMissingCovers_Call) Run(run func(ctx context.Context, code string)) *MockExpansionSetRepository_ListMissingCovers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockExpansionSetRepository_ListMissingCovers_Call) Return(_a0 []entity.ExpansionSet, _a1 error) *MockExpansionSetRepository_ListMissingCovers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpansionSetRepository_ListMissingCovers_Call) RunAndReturn(run func(context.Context, string) ([]entity.ExpansionSet, error)) *MockExpansionSetRepository_ListMissingCovers_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMany provides a mock function with given fields: ctx, models
func (_m *MockExpansionSetRepository) SaveMany(ctx context.Context, models []entity.ExpansionSet) ([]entity.ExpansionSet, error) {
	ret := _m.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 []entity.ExpansionSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.ExpansionSet) ([]entity.ExpansionSet, error)); ok {
		return rf(ctx, models)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []entity.ExpansionSet) []entity.ExpansionSet); ok {
		r0 = rf(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ExpansionSet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []entity.ExpansionSet) error); ok {
		r1 = rf(ctx, models)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpansionSetRepository_SaveMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMany'
type MockExpansionSetRepository_SaveMany_Call struct {
	*mock.Call
}

// SaveMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []entity.ExpansionSet
func (_e *MockExpansionSetRepository_Expecter) SaveMany(ctx interface{}, models interface{}) *MockExpansionSetRepository_SaveMany_Call {
	return &MockExpansionSetRepository_SaveMany_Call{Call: _e.mock.On("SaveMany", ctx, models)}
}

func (_c *MockExpansionSetRepository_SaveMany_Call) Run(run func(ctx context.Context, models []entity.ExpansionSet)) *MockExpansionSetRepository_SaveMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.ExpansionSet))
	})
	return _c
}

func (_c *MockExpansionSetRepository_SaveMany_Call) Return(_a0 []entity.ExpansionSet, _a1 error) *MockExpansionSetRepository_SaveMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpansionSetRepository_SaveMany_Call) RunAndReturn(run func(context.Context, []entity.ExpansionSet) ([]entity.ExpansionSet, error)) *MockExpansionSetRepository_SaveMany_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, model
func (_m *MockExpansionSetRepository) Update(ctx context.Context, model entity.ExpansionSet) (entity.ExpansionSet, error) {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.ExpansionSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ExpansionSet) (entity.ExpansionSet, error)); ok {
		return rf(ctx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ExpansionSet) entity.ExpansionSet); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Get(0).(entity.ExpansionSet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ExpansionSet) error); ok {
		r1 = rf(ctx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpansionSetRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockExpansionSetRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - model entity.ExpansionSet
func (_e *MockExpansionSetRepository_Expecter) Update(ctx interface{}, model interface{}) *MockExpansionSetRepository_Update_Call {
	return &MockExpansionSetRepository_Update_Call{Call: _e.mock.On("Update", ctx, model)}
}

func (_c *MockExpansionSetRepository_Update_Call) Run(run func(ctx context.Context, model entity.ExpansionSet)) *MockExpansionSetRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ExpansionSet))
	})
	return _c
}

func (_c *MockExpansionSetRepository_Update_Call) Return(_a0 entity.ExpansionSet, _a1 error) *MockExpansionSetRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpansionSetRepository_Update_Call) RunAndReturn(run func(context.Context, entity.ExpansionSet) (entity.ExpansionSet, error)) *MockExpansionSetRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExpansionSetRepository creates a new instance of MockExpansionSetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpansionSetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpansionSetRepository {
	mock := &MockExpansionSetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
