// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	dto "github.com/itsLeonB/cardstack/backend/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockIdentityCache is an autogenerated mock type for the IdentityCache type
type MockIdentityCache struct {
	mock.Mock
}

type MockIdentityCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentityCache) EXPECT() *MockIdentityCache_Expecter {
	return &MockIdentityCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: identity
func (_m *MockIdentityCache) Get(identity dto.AuthIdentity) (dto.CallerIdentity, bool) {
	ret := _m.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 dto.CallerIdentity
	var r1 bool
	if rf, ok := ret.Get(0).(func(dto.AuthIdentity) (dto.CallerIdentity, bool)); ok {
		return rf(identity)
	}
	if rf, ok := ret.Get(0).(func(dto.AuthIdentity) dto.CallerIdentity); ok {
		r0 = rf(identity)
	} else {
		r0 = ret.Get(0).(dto.CallerIdentity)
	}

	if rf, ok := ret.Get(1).(func(dto.AuthIdentity) bool); ok {
		r1 = rf(identity)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockIdentityCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIdentityCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - identity dto.AuthIdentity
func (_e *MockIdentityCache_Expecter) Get(identity interface{}) *MockIdentityCache_Get_Call {
	return &MockIdentityCache_Get_Call{Call: _e.mock.On("Get", identity)}
}

func (_c *MockIdentityCache_Get_Call) Run(run func(identity dto.AuthIdentity)) *MockIdentityCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.AuthIdentity))
	})
	return _c
}

func (_c *MockIdentityCache_Get_Call) Return(_a0 dto.CallerIdentity, _a1 bool) *MockIdentityCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityCache_Get_Call) RunAndReturn(run func(dto.AuthIdentity) (dto.CallerIdentity, bool)) *MockIdentityCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: identity, caller
func (_m *MockIdentityCache) Set(identity dto.AuthIdentity, caller dto.CallerIdentity) {
	_m.Called(identity, caller)
}

// MockIdentityCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockIdentityCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - identity dto.AuthIdentity
//   - caller dto.CallerIdentity
func (_e *MockIdentityCache_Expecter) Set(identity interface{}, caller interface{}) *MockIdentityCache_Set_Call {
	return &MockIdentityCache_Set_Call{Call: _e.mock.On("Set", identity, caller)}
}

func (_c *MockIdentityCache_Set_Call) Run(run func(identity dto.AuthIdentity, caller dto.CallerIdentity)) *MockIdentityCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.AuthIdentity), args[1].(dto.CallerIdentity))
	})
	return _c
}

func (_c *MockIdentityCache_Set_Call) Return() *MockIdentityCache_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIdentityCache_Set_Call) RunAndReturn(run func(dto.AuthIdentity, dto.CallerIdentity)) *MockIdentityCache_Set_Call {
	_c.Run(run)
	return _c
}

// NewMockIdentityCache creates a new instance of MockIdentityCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentityCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdentityCache {
	mock := &MockIdentityCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
