// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockImageEmbedder is an autogenerated mock type for the ImageEmbedder type
type MockImageEmbedder struct {
	mock.Mock
}

type MockImageEmbedder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageEmbedder) EXPECT() *MockImageEmbedder_Expecter {
	return &MockImageEmbedder_Expecter{mock: &_m.Mock}
}

// Embed provides a mock function with given fields: ctx, mimeType, data
func (_m *MockImageEmbedder) Embed(ctx context.Context, mimeType string, data []byte) ([]float32, error) {
	ret := _m.Called(ctx, mimeType, data)

	if len(ret) == 0 {
		panic("no return value specified for Embed")
	}

	var r0 []float32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) ([]float32, error)); ok {
		return rf(ctx, mimeType, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) []float32); ok {
		r0 = rf(ctx, mimeType, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, mimeType, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageEmbedder_Embed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Embed'
type MockImageEmbedder_Embed_Call struct {
	*mock.Call
}

// Embed is a helper method to define mock.On call
//   - ctx context.Context
//   - mimeType string
//   - data []byte
func (_e *MockImageEmbedder_Expecter) Embed(ctx interface{}, mimeType interface{}, data interface{}) *MockImageEmbedder_Embed_Call {
	return &MockImageEmbedder_Embed_Call{Call: _e.mock.On("Embed", ctx, mimeType, data)}
}

func (_c *MockImageEmbedder_Embed_Call) Run(run func(ctx context.Context, mimeType string, data []byte)) *MockImageEmbedder_Embed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockImageEmbedder_Embed_Call) Return(_a0 []float32, _a1 error) *MockImageEmbedder_Embed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageEmbedder_Embed_Call) RunAndReturn(run func(context.Context, string, []byte) ([]float32, error)) *MockImageEmbedder_Embed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageEmbedder creates a new instance of MockImageEmbedder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageEmbedder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageEmbedder {
	mock := &MockImageEmbedder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
