// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/itsLeonB/cardstack/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/itsLeonB/cardstack/backend/internal/domain/repository"

	uuid "github.com/google/uuid"
)

// MockInventoryRepository is an autogenerated mock type for the InventoryRepository type
type MockInventoryRepository struct {
	mock.Mock
}

type MockInventoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryRepository) EXPECT() *MockInventoryRepository_Expecter {
	return &MockInventoryRepository_Expecter{mock: &_m.Mock}
}

// CardExists provides a mock function with given fields: ctx, cardID
func (_m *MockInventoryRepository) CardExists(ctx context.Context, cardID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, cardID)

	if len(ret) == 0 {
		panic("no return value specified for CardExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, cardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, cardID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, cardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryRepository_CardExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CardExists'
type MockInventoryRepository_CardExists_Call struct {
	*mock.Call
}

// CardExists is a helper method to define mock.On call
//   - ctx context.Context
//   - cardID uuid.UUID
func (_e *MockInventoryRepository_Expecter) CardExists(ctx interface{}, cardID interface{}) *MockInventoryRepository_CardExists_Call {
	return &MockInventoryRepository_CardExists_Call{Call: _e.mock.On("CardExists", ctx, cardID)}
}

func (_c *MockInventoryRepository_CardExists_Call) Run(run func(ctx context.Context, cardID uuid.UUID)) *MockInventoryRepository_CardExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockInventoryRepository_CardExists_Call) Return(_a0 bool, _a1 error) *MockInventoryRepository_CardExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryRepository_CardExists_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *MockInventoryRepository_CardExists_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEntry provides a mock function with given fields: ctx, collectionID, cardID
func (_m *MockInventoryRepository) DeleteEntry(ctx context.Context, collectionID uuid.UUID, cardID uuid.UUID) error {
	ret := _m.Called(ctx, collectionID, cardID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, collectionID, cardID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInventoryRepository_DeleteEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEntry'
type MockInventoryRepository_DeleteEntry_Call struct {
	*mock.Call
}

// DeleteEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - collectionID uuid.UUID
//   - cardID uuid.UUID
func (_e *MockInventoryRepository_Expecter) DeleteEntry(ctx interface{}, collectionID interface{}, cardID interface{}) *MockInventoryRepository_DeleteEntry_Call {
	return &MockInventoryRepository_DeleteEntry_Call{Call: _e.mock.On("DeleteEntry", ctx, collectionID, cardID)}
}

func (_c *MockInventoryRepository_DeleteEntry_Call) Run(run func(ctx context.Context, collectionID uuid.UUID, cardID uuid.UUID)) *MockInventoryRepository_DeleteEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockInventoryRepository_DeleteEntry_Call) Return(_a0 error) *MockInventoryRepository_DeleteEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInventoryRepository_DeleteEntry_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockInventoryRepository_DeleteEntry_Call {
	_c.Call.Return(run)
	return _c
}

// FindEntry provides a mock function with given fields: ctx, collectionID, cardID
func (_m *MockInventoryRepository) FindEntry(ctx context.Context, collectionID uuid.UUID, cardID uuid.UUID) (entity.InventoryEntry, error) {
	ret := _m.Called(ctx, collectionID, cardID)

	if len(ret) == 0 {
		panic("no return value specified for FindEntry")
	}

	var r0 entity.InventoryEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (entity.InventoryEntry, error)); ok {
		return rf(ctx, collectionID, cardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) entity.InventoryEntry); ok {
		r0 = rf(ctx, collectionID, cardID)
	} else {
		r0 = ret.Get(0).(entity.InventoryEntry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, collectionID, cardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryRepository_FindEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindEntry'
type MockInventoryRepository_FindEntry_Call struct {
	*mock.Call
}

// FindEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - collectionID uuid.UUID
//   - cardID uuid.UUID
func (_e *MockInventoryRepository_Expecter) FindEntry(ctx interface{}, collectionID interface{}, cardID interface{}) *MockInventoryRepository_FindEntry_Call {
	return &MockInventoryRepository_FindEntry_Call{Call: _e.mock.On("FindEntry", ctx, collectionID, cardID)}
}

func (_c *MockInventoryRepository_FindEntry_Call) Run(run func(ctx context.Context, collectionID uuid.UUID, cardID uuid.UUID)) *MockInventoryRepository_FindEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockInventoryRepository_FindEntry_Call) Return(_a0 entity.InventoryEntry, _a1 error) *MockInventoryRepository_FindEntry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryRepository_FindEntry_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (entity.InventoryEntry, error)) *MockInventoryRepository_FindEntry_Call {
	_c.Call.Return(run)
	return _c
}

// InsertEntry provides a mock function with given fields: ctx, entry
func (_m *MockInventoryRepository) InsertEntry(ctx context.Context, entry entity.InventoryEntry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for InsertEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.InventoryEntry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInventoryRepository_InsertEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertEntry'
type MockInventoryRepository_InsertEntry_Call struct {
	*mock.Call
}

// InsertEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - entry entity.InventoryEntry
func (_e *MockInventoryRepository_Expecter) InsertEntry(ctx interface{}, entry interface{}) *MockInventoryRepository_InsertEntry_Call {
	return &MockInventoryRepository_InsertEntry_Call{Call: _e.mock.On("InsertEntry", ctx, entry)}
}

func (_c *MockInventoryRepository_InsertEntry_Call) Run(run func(ctx context.Context, entry entity.InventoryEntry)) *MockInventoryRepository_InsertEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.InventoryEntry))
	})
	return _c
}

func (_c *MockInventoryRepository_InsertEntry_Call) Return(_a0 error) *MockInventoryRepository_InsertEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInventoryRepository_InsertEntry_Call) RunAndReturn(run func(context.Context, entity.InventoryEntry) error) *MockInventoryRepository_InsertEntry_Call {
	_c.Call.Return(run)
	return _c
}

// ListItems provides a mock function with given fields: ctx, collectionID
func (_m *MockInventoryRepository) ListItems(ctx context.Context, collectionID uuid.UUID) ([]repository.InventoryItemResult, error) {
	ret := _m.Called(ctx, collectionID)

	if len(ret) == 0 {
		panic("no return value specified for ListItems")
	}

	var r0 []repository.InventoryItemResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.InventoryItemResult, error)); ok {
		return rf(ctx, collectionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.InventoryItemResult); ok {
		r0 = rf(ctx, collectionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.InventoryItemResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, collectionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryRepository_ListItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItems'
type MockInventoryRepository_ListItems_Call struct {
	*mock.Call
}

// ListItems is a helper method to define mock.On call
//   - ctx context.Context
//   - collectionID uuid.UUID
func (_e *MockInventoryRepository_Expecter) ListItems(ctx interface{}, collectionID interface{}) *MockInventoryRepository_ListItems_Call {
	return &MockInventoryRepository_ListItems_Call{Call: _e.mock.On("ListItems", ctx, collectionID)}
}

func (_c *MockInventoryRepository_ListItems_Call) Run(run func(ctx context.Context, collectionID uuid.UUID)) *MockInventoryRepository_ListItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockInventoryRepository_ListItems_Call) Return(_a0 []repository.InventoryItemResult, _a1 error) *MockInventoryRepository_ListItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryRepository_ListItems_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]repository.InventoryItemResult, error)) *MockInventoryRepository_ListItems_Call {
	_c.Call.Return(run)
	return _c
}

// SumQuantity provides a mock function with given fields: ctx, collectionID
func (_m *MockInventoryRepository) SumQuantity(ctx context.Context, collectionID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, collectionID)

	if len(ret) == 0 {
		panic("no return value specified for SumQuantity")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, collectionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, collectionID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, collectionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryRepository_SumQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumQuantity'
type MockInventoryRepository_SumQuantity_Call struct {
	*mock.Call
}

// SumQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - collectionID uuid.UUID
func (_e *MockInventoryRepository_Expecter) SumQuantity(ctx interface{}, collectionID interface{}) *MockInventoryRepository_SumQuantity_Call {
	return &MockInventoryRepository_SumQuantity_Call{Call: _e.mock.On("SumQuantity", ctx, collectionID)}
}

func (_c *MockInventoryRepository_SumQuantity_Call) Run(run func(ctx context.Context, collectionID uuid.UUID)) *MockInventoryRepository_SumQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockInventoryRepository_SumQuantity_Call) Return(_a0 int, _a1 error) *MockInventoryRepository_SumQuantity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryRepository_SumQuantity_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockInventoryRepository_SumQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQuantity provides a mock function with given fields: ctx, collectionID, cardID, quantity
func (_m *MockInventoryRepository) UpdateQuantity(ctx context.Context, collectionID uuid.UUID, cardID uuid.UUID, quantity int) error {
	ret := _m.Called(ctx, collectionID, cardID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuantity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = rf(ctx, collectionID, cardID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInventoryRepository_UpdateQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQuantity'
type MockInventoryRepository_UpdateQuantity_Call struct {
	*mock.Call
}

// UpdateQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - collectionID uuid.UUID
//   - cardID uuid.UUID
//   - quantity int
func (_e *MockInventoryRepository_Expecter) UpdateQuantity(ctx interface{}, collectionID interface{}, cardID interface{}, quantity interface{}) *MockInventoryRepository_UpdateQuantity_Call {
	return &MockInventoryRepository_UpdateQuantity_Call{Call: _e.mock.On("UpdateQuantity", ctx, collectionID, cardID, quantity)}
}

func (_c *MockInventoryRepository_UpdateQuantity_Call) Run(run func(ctx context.Context, collectionID uuid.UUID, cardID uuid.UUID, quantity int)) *MockInventoryRepository_UpdateQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int))
	})
	return _c
}

func (_c *MockInventoryRepository_UpdateQuantity_Call) Return(_a0 error) *MockInventoryRepository_UpdateQuantity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInventoryRepository_UpdateQuantity_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int) error) *MockInventoryRepository_UpdateQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// WithLockedCollection provides a mock function with given fields: ctx, profileID, collectionID, fn
func (_m *MockInventoryRepository) WithLockedCollection(ctx context.Context, profileID uuid.UUID, collectionID uuid.UUID, fn func(repository.InventoryRepository, entity.Collection) error) error {
	ret := _m.Called(ctx, profileID, collectionID, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithLockedCollection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, func(repository.InventoryRepository, entity.Collection) error) error); ok {
		r0 = rf(ctx, profileID, collectionID, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInventoryRepository_WithLockedCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithLockedCollection'
type MockInventoryRepository_WithLockedCollection_Call struct {
	*mock.Call
}

// WithLockedCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uuid.UUID
//   - collectionID uuid.UUID
//   - fn func(repository.InventoryRepository , entity.Collection) error
func (_e *MockInventoryRepository_Expecter) WithLockedCollection(ctx interface{}, profileID interface{}, collectionID interface{}, fn interface{}) *MockInventoryRepository_WithLockedCollection_Call {
	return &MockInventoryRepository_WithLockedCollection_Call{Call: _e.mock.On("WithLockedCollection", ctx, profileID, collectionID, fn)}
}

func (_c *MockInventoryRepository_WithLockedCollection_Call) Run(run func(ctx context.Context, profileID uuid.UUID, collectionID uuid.UUID, fn func(repository.InventoryRepository, entity.Collection) error)) *MockInventoryRepository_WithLockedCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(func(repository.InventoryRepository, entity.Collection) error))
	})
	return _c
}

func (_c *MockInventoryRepository_WithLockedCollection_Call) Return(_a0 error) *MockInventoryRepository_WithLockedCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInventoryRepository_WithLockedCollection_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, func(repository.InventoryRepository, entity.Collection) error) error) *MockInventoryRepository_WithLockedCollection_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInventoryRepository creates a new instance of MockInventoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryRepository {
	mock := &MockInventoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
