// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/itsLeonB/cardstack/backend/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockInventoryService is an autogenerated mock type for the InventoryService type
type MockInventoryService struct {
	mock.Mock
}

type MockInventoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryService) EXPECT() *MockInventoryService_Expecter {
	return &MockInventoryService_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, req
func (_m *MockInventoryService) Add(ctx context.Context, req dto.InventoryEntryRequest) (dto.InventoryEntry, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 dto.InventoryEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.InventoryEntryRequest) (dto.InventoryEntry, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.InventoryEntryRequest) dto.InventoryEntry); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.InventoryEntry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.InventoryEntryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryService_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockInventoryService_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.InventoryEntryRequest
func (_e *MockInventoryService_Expecter) Add(ctx interface{}, req interface{}) *MockInventoryService_Add_Call {
	return &MockInventoryService_Add_Call{Call: _e.mock.On("Add", ctx, req)}
}

func (_c *MockInventoryService_Add_Call) Run(run func(ctx context.Context, req dto.InventoryEntryRequest)) *MockInventoryService_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.InventoryEntryRequest))
	})
	return _c
}

func (_c *MockInventoryService_Add_Call) Return(_a0 dto.InventoryEntry, _a1 error) *MockInventoryService_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryService_Add_Call) RunAndReturn(run func(context.Context, dto.InventoryEntryRequest) (dto.InventoryEntry, error)) *MockInventoryService_Add_Call {
	_c.Call.Return(run)
	return _c
}

// BulkUpdate provides a mock function with given fields: ctx, req
func (_m *MockInventoryService) BulkUpdate(ctx context.Context, req dto.InventoryBulkUpdateRequest) ([]dto.InventoryChangeResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpdate")
	}

	var r0 []dto.InventoryChangeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.InventoryBulkUpdateRequest) ([]dto.InventoryChangeResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.InventoryBulkUpdateRequest) []dto.InventoryChangeResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.InventoryChangeResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.InventoryBulkUpdateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryService_BulkUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpdate'
type MockInventoryService_BulkUpdate_Call struct {
	*mock.Call
}

// BulkUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.InventoryBulkUpdateRequest
func (_e *MockInventoryService_Expecter) BulkUpdate(ctx interface{}, req interface{}) *MockInventoryService_BulkUpdate_Call {
	return &MockInventoryService_BulkUpdate_Call{Call: _e.mock.On("BulkUpdate", ctx, req)}
}

func (_c *MockInventoryService_BulkUpdate_Call) Run(run func(ctx context.Context, req dto.InventoryBulkUpdateRequest)) *MockInventoryService_BulkUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.InventoryBulkUpdateRequest))
	})
	return _c
}

func (_c *MockInventoryService_BulkUpdate_Call) Return(_a0 []dto.InventoryChangeResult, _a1 error) *MockInventoryService_BulkUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryService_BulkUpdate_Call) RunAndReturn(run func(context.Context, dto.InventoryBulkUpdateRequest) ([]dto.InventoryChangeResult, error)) *MockInventoryService_BulkUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, req
func (_m *MockInventoryService) List(ctx context.Context, req dto.InventoryListRequest) ([]dto.InventoryItem, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []dto.InventoryItem
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.InventoryListRequest) ([]dto.InventoryItem, dto.PaginationMeta, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.InventoryListRequest) []dto.InventoryItem); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.InventoryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.InventoryListRequest) dto.PaginationMeta); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.InventoryListRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockInventoryService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockInventoryService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.InventoryListRequest
func (_e *MockInventoryService_Expecter) List(ctx interface{}, req interface{}) *MockInventoryService_List_Call {
	return &MockInventoryService_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *MockInventoryService_List_Call) Run(run func(ctx context.Context, req dto.InventoryListRequest)) *MockInventoryService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.InventoryListRequest))
	})
	return _c
}

func (_c *MockInventoryService_List_Call) Return(_a0 []dto.InventoryItem, _a1 dto.PaginationMeta, _a2 error) *MockInventoryService_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockInventoryService_List_Call) RunAndReturn(run func(context.Context, dto.InventoryListRequest) ([]dto.InventoryItem, dto.PaginationMeta, error)) *MockInventoryService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListCardHoldings provides a mock function with given fields: ctx, req
func (_m *MockInventoryService) ListCardHoldings(ctx context.Context, req dto.CardHoldingsRequest) ([]dto.CardHolding, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListCardHoldings")
	}

	var r0 []dto.CardHolding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CardHoldingsRequest) ([]dto.CardHolding, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CardHoldingsRequest) []dto.CardHolding); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CardHolding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CardHoldingsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryService_ListCardHoldings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCardHoldings'
type MockInventoryService_ListCardHoldings_Call struct {
	*mock.Call
}

// ListCardHoldings is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CardHoldingsRequest
func (_e *MockInventoryService_Expecter) ListCardHoldings(ctx interface{}, req interface{}) *MockInventoryService_ListCardHoldings_Call {
	return &MockInventoryService_ListCardHoldings_Call{Call: _e.mock.On("ListCardHoldings", ctx, req)}
}

func (_c *MockInventoryService_ListCardHoldings_Call) Run(run func(ctx context.Context, req dto.CardHoldingsRequest)) *MockInventoryService_ListCardHoldings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CardHoldingsRequest))
	})
	return _c
}

func (_c *MockInventoryService_ListCardHoldings_Call) Return(_a0 []dto.CardHolding, _a1 error) *MockInventoryService_ListCardHoldings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryService_ListCardHoldings_Call) RunAndReturn(run func(context.Context, dto.CardHoldingsRequest) ([]dto.CardHolding, error)) *MockInventoryService_ListCardHoldings_Call {
	_c.Call.Return(run)
	return _c
}

// ListFacets provides a mock function with given fields: ctx, req
func (_m *MockInventoryService) ListFacets(ctx context.Context, req dto.InventoryListRequest) (dto.CatalogFacets, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListFacets")
	}

	var r0 dto.CatalogFacets
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.InventoryListRequest) (dto.CatalogFacets, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.InventoryListRequest) dto.CatalogFacets); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.CatalogFacets)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.InventoryListRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryService_ListFacets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFacets'
type MockInventoryService_ListFacets_Call struct {
	*mock.Call
}

// ListFacets is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.InventoryListRequest
func (_e *MockInventoryService_Expecter) ListFacets(ctx interface{}, req interface{}) *MockInventoryService_ListFacets_Call {
	return &MockInventoryService_ListFacets_Call{Call: _e.mock.On("ListFacets", ctx, req)}
}

func (_c *MockInventoryService_ListFacets_Call) Run(run func(ctx context.Context, req dto.InventoryListRequest)) *MockInventoryService_ListFacets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.InventoryListRequest))
	})
	return _c
}

func (_c *MockInventoryService_ListFacets_Call) Return(_a0 dto.CatalogFacets, _a1 error) *MockInventoryService_ListFacets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryService_ListFacets_Call) RunAndReturn(run func(context.Context, dto.InventoryListRequest) (dto.CatalogFacets, error)) *MockInventoryService_ListFacets_Call {
	_c.Call.Return(run)
	return _c
}

// ListMasterFacets provides a mock function with given fields: ctx, req
func (_m *MockInventoryService) ListMasterFacets(ctx context.Context, req dto.MasterInventoryRequest) (dto.CatalogFacets, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListMasterFacets")
	}

	var r0 dto.CatalogFacets
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.MasterInventoryRequest) (dto.CatalogFacets, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.MasterInventoryRequest) dto.CatalogFacets); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.CatalogFacets)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.MasterInventoryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryService_ListMasterFacets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMasterFacets'
type MockInventoryService_ListMasterFacets_Call struct {
	*mock.Call
}

// ListMasterFacets is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.MasterInventoryRequest
func (_e *MockInventoryService_Expecter) ListMasterFacets(ctx interface{}, req interface{}) *MockInventoryService_ListMasterFacets_Call {
	return &MockInventoryService_ListMasterFacets_Call{Call: _e.mock.On("ListMasterFacets", ctx, req)}
}

func (_c *MockInventoryService_ListMasterFacets_Call) Run(run func(ctx context.Context, req dto.MasterInventoryRequest)) *MockInventoryService_ListMasterFacets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.MasterInventoryRequest))
	})
	return _c
}

func (_c *MockInventoryService_ListMasterFacets_Call) Return(_a0 dto.CatalogFacets, _a1 error) *MockInventoryService_ListMasterFacets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryService_ListMasterFacets_Call) RunAndReturn(run func(context.Context, dto.MasterInventoryRequest) (dto.CatalogFacets, error)) *MockInventoryService_ListMasterFacets_Call {
	_c.Call.Return(run)
	return _c
}

// ListMasterInventory provides a mock function with given fields: ctx, req
func (_m *MockInventoryService) ListMasterInventory(ctx context.Context, req dto.MasterInventoryRequest) ([]dto.InventoryItem, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListMasterInventory")
	}

	var r0 []dto.InventoryItem
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.MasterInventoryRequest) ([]dto.InventoryItem, dto.PaginationMeta, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.MasterInventoryRequest) []dto.InventoryItem); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.InventoryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.MasterInventoryRequest) dto.PaginationMeta); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.MasterInventoryRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockInventoryService_ListMasterInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMasterInventory'
type MockInventoryService_ListMasterInventory_Call struct {
	*mock.Call
}

// ListMasterInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.MasterInventoryRequest
func (_e *MockInventoryService_Expecter) ListMasterInventory(ctx interface{}, req interface{}) *MockInventoryService_ListMasterInventory_Call {
	return &MockInventoryService_ListMasterInventory_Call{Call: _e.mock.On("ListMasterInventory", ctx, req)}
}

func (_c *MockInventoryService_ListMasterInventory_Call) Run(run func(ctx context.Context, req dto.MasterInventoryRequest)) *MockInventoryService_ListMasterInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.MasterInventoryRequest))
	})
	return _c
}

func (_c *MockInventoryService_ListMasterInventory_Call) Return(_a0 []dto.InventoryItem, _a1 dto.PaginationMeta, _a2 error) *MockInventoryService_ListMasterInventory_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockInventoryService_ListMasterInventory_Call) RunAndReturn(run func(context.Context, dto.MasterInventoryRequest) ([]dto.InventoryItem, dto.PaginationMeta, error)) *MockInventoryService_ListMasterInventory_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, req
func (_m *MockInventoryService) Remove(ctx context.Context, req dto.InventoryEntryLookup) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.InventoryEntryLookup) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInventoryService_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockInventoryService_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.InventoryEntryLookup
func (_e *MockInventoryService_Expecter) Remove(ctx interface{}, req interface{}) *MockInventoryService_Remove_Call {
	return &MockInventoryService_Remove_Call{Call: _e.mock.On("Remove", ctx, req)}
}

func (_c *MockInventoryService_Remove_Call) Run(run func(ctx context.Context, req dto.InventoryEntryLookup)) *MockInventoryService_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.InventoryEntryLookup))
	})
	return _c
}

func (_c *MockInventoryService_Remove_Call) Return(_a0 error) *MockInventoryService_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInventoryService_Remove_Call) RunAndReturn(run func(context.Context, dto.InventoryEntryLookup) error) *MockInventoryService_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQuantity provides a mock function with given fields: ctx, req
func (_m *MockInventoryService) UpdateQuantity(ctx context.Context, req dto.InventoryEntryRequest) (dto.InventoryEntry, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuantity")
	}

	var r0 dto.InventoryEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.InventoryEntryRequest) (dto.InventoryEntry, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.InventoryEntryRequest) dto.InventoryEntry); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.InventoryEntry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.InventoryEntryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryService_UpdateQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQuantity'
type MockInventoryService_UpdateQuantity_Call struct {
	*mock.Call
}

// UpdateQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.InventoryEntryRequest
func (_e *MockInventoryService_Expecter) UpdateQuantity(ctx interface{}, req interface{}) *MockInventoryService_UpdateQuantity_Call {
	return &MockInventoryService_UpdateQuantity_Call{Call: _e.mock.On("UpdateQuantity", ctx, req)}
}

func (_c *MockInventoryService_UpdateQuantity_Call) Run(run func(ctx context.Context, req dto.InventoryEntryRequest)) *MockInventoryService_UpdateQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.InventoryEntryRequest))
	})
	return _c
}

func (_c *MockInventoryService_UpdateQuantity_Call) Return(_a0 dto.InventoryEntry, _a1 error) *MockInventoryService_UpdateQuantity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryService_UpdateQuantity_Call) RunAndReturn(run func(context.Context, dto.InventoryEntryRequest) (dto.InventoryEntry, error)) *MockInventoryService_UpdateQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInventoryService creates a new instance of MockInventoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryService {
	mock := &MockInventoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
