// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/itsLeonB/cardstack/backend/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockInventoryService is an autogenerated mock type for the InventoryService type
type MockInventoryService struct {
	mock.Mock
}

type MockInventoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryService) EXPECT() *MockInventoryService_Expecter {
	return &MockInventoryService_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, profileID, collectionID, req
func (_m *MockInventoryService) Add(ctx context.Context, profileID uuid.UUID, collectionID uuid.UUID, req dto.InventoryEntryRequest) (dto.InventoryEntry, error) {
	ret := _m.Called(ctx, profileID, collectionID, req)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 dto.InventoryEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.InventoryEntryRequest) (dto.InventoryEntry, error)); ok {
		return rf(ctx, profileID, collectionID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.InventoryEntryRequest) dto.InventoryEntry); ok {
		r0 = rf(ctx, profileID, collectionID, req)
	} else {
		r0 = ret.Get(0).(dto.InventoryEntry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.InventoryEntryRequest) error); ok {
		r1 = rf(ctx, profileID, collectionID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryService_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockInventoryService_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uuid.UUID
//   - collectionID uuid.UUID
//   - req dto.InventoryEntryRequest
func (_e *MockInventoryService_Expecter) Add(ctx interface{}, profileID interface{}, collectionID interface{}, req interface{}) *MockInventoryService_Add_Call {
	return &MockInventoryService_Add_Call{Call: _e.mock.On("Add", ctx, profileID, collectionID, req)}
}

func (_c *MockInventoryService_Add_Call) Run(run func(ctx context.Context, profileID uuid.UUID, collectionID uuid.UUID, req dto.InventoryEntryRequest)) *MockInventoryService_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(dto.InventoryEntryRequest))
	})
	return _c
}

func (_c *MockInventoryService_Add_Call) Return(_a0 dto.InventoryEntry, _a1 error) *MockInventoryService_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryService_Add_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, dto.InventoryEntryRequest) (dto.InventoryEntry, error)) *MockInventoryService_Add_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, profileID, collectionID
func (_m *MockInventoryService) List(ctx context.Context, profileID uuid.UUID, collectionID uuid.UUID) ([]dto.InventoryItem, error) {
	ret := _m.Called(ctx, profileID, collectionID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []dto.InventoryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]dto.InventoryItem, error)); ok {
		return rf(ctx, profileID, collectionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []dto.InventoryItem); ok {
		r0 = rf(ctx, profileID, collectionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.InventoryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, profileID, collectionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockInventoryService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uuid.UUID
//   - collectionID uuid.UUID
func (_e *MockInventoryService_Expecter) List(ctx interface{}, profileID interface{}, collectionID interface{}) *MockInventoryService_List_Call {
	return &MockInventoryService_List_Call{Call: _e.mock.On("List", ctx, profileID, collectionID)}
}

func (_c *MockInventoryService_List_Call) Run(run func(ctx context.Context, profileID uuid.UUID, collectionID uuid.UUID)) *MockInventoryService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockInventoryService_List_Call) Return(_a0 []dto.InventoryItem, _a1 error) *MockInventoryService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryService_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]dto.InventoryItem, error)) *MockInventoryService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, profileID, collectionID, cardID
func (_m *MockInventoryService) Remove(ctx context.Context, profileID uuid.UUID, collectionID uuid.UUID, cardID uuid.UUID) error {
	ret := _m.Called(ctx, profileID, collectionID, cardID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, profileID, collectionID, cardID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInventoryService_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockInventoryService_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uuid.UUID
//   - collectionID uuid.UUID
//   - cardID uuid.UUID
func (_e *MockInventoryService_Expecter) Remove(ctx interface{}, profileID interface{}, collectionID interface{}, cardID interface{}) *MockInventoryService_Remove_Call {
	return &MockInventoryService_Remove_Call{Call: _e.mock.On("Remove", ctx, profileID, collectionID, cardID)}
}

func (_c *MockInventoryService_Remove_Call) Run(run func(ctx context.Context, profileID uuid.UUID, collectionID uuid.UUID, cardID uuid.UUID)) *MockInventoryService_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockInventoryService_Remove_Call) Return(_a0 error) *MockInventoryService_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInventoryService_Remove_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockInventoryService_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQuantity provides a mock function with given fields: ctx, profileID, collectionID, cardID, quantity
func (_m *MockInventoryService) UpdateQuantity(ctx context.Context, profileID uuid.UUID, collectionID uuid.UUID, cardID uuid.UUID, quantity int) (dto.InventoryEntry, error) {
	ret := _m.Called(ctx, profileID, collectionID, cardID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuantity")
	}

	var r0 dto.InventoryEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int) (dto.InventoryEntry, error)); ok {
		return rf(ctx, profileID, collectionID, cardID, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int) dto.InventoryEntry); ok {
		r0 = rf(ctx, profileID, collectionID, cardID, quantity)
	} else {
		r0 = ret.Get(0).(dto.InventoryEntry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int) error); ok {
		r1 = rf(ctx, profileID, collectionID, cardID, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryService_UpdateQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQuantity'
type MockInventoryService_UpdateQuantity_Call struct {
	*mock.Call
}

// UpdateQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uuid.UUID
//   - collectionID uuid.UUID
//   - cardID uuid.UUID
//   - quantity int
func (_e *MockInventoryService_Expecter) UpdateQuantity(ctx interface{}, profileID interface{}, collectionID interface{}, cardID interface{}, quantity interface{}) *MockInventoryService_UpdateQuantity_Call {
	return &MockInventoryService_UpdateQuantity_Call{Call: _e.mock.On("UpdateQuantity", ctx, profileID, collectionID, cardID, quantity)}
}

func (_c *MockInventoryService_UpdateQuantity_Call) Run(run func(ctx context.Context, profileID uuid.UUID, collectionID uuid.UUID, cardID uuid.UUID, quantity int)) *MockInventoryService_UpdateQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(int))
	})
	return _c
}

func (_c *MockInventoryService_UpdateQuantity_Call) Return(_a0 dto.InventoryEntry, _a1 error) *MockInventoryService_UpdateQuantity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryService_UpdateQuantity_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int) (dto.InventoryEntry, error)) *MockInventoryService_UpdateQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInventoryService creates a new instance of MockInventoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryService {
	mock := &MockInventoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
