// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/itsLeonB/cardstack/backend/internal/domain/entity"
	crud "github.com/itsLeonB/go-crud"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	repository "github.com/itsLeonB/cardstack/backend/internal/domain/repository"

	uuid "github.com/google/uuid"
)

// MockInventoryRepository is an autogenerated mock type for the InventoryRepository type
type MockInventoryRepository struct {
	mock.Mock
}

type MockInventoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryRepository) EXPECT() *MockInventoryRepository_Expecter {
	return &MockInventoryRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, model
func (_m *MockInventoryRepository) Delete(ctx context.Context, model entity.InventoryEntry) error {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.InventoryEntry) error); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInventoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockInventoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - model entity.InventoryEntry
func (_e *MockInventoryRepository_Expecter) Delete(ctx interface{}, model interface{}) *MockInventoryRepository_Delete_Call {
	return &MockInventoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, model)}
}

func (_c *MockInventoryRepository_Delete_Call) Run(run func(ctx context.Context, model entity.InventoryEntry)) *MockInventoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.InventoryEntry))
	})
	return _c
}

func (_c *MockInventoryRepository_Delete_Call) Return(_a0 error) *MockInventoryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInventoryRepository_Delete_Call) RunAndReturn(run func(context.Context, entity.InventoryEntry) error) *MockInventoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function with given fields: ctx, models
func (_m *MockInventoryRepository) DeleteMany(ctx context.Context, models []entity.InventoryEntry) error {
	ret := _m.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.InventoryEntry) error); ok {
		r0 = rf(ctx, models)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInventoryRepository_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type MockInventoryRepository_DeleteMany_Call struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []entity.InventoryEntry
func (_e *MockInventoryRepository_Expecter) DeleteMany(ctx interface{}, models interface{}) *MockInventoryRepository_DeleteMany_Call {
	return &MockInventoryRepository_DeleteMany_Call{Call: _e.mock.On("DeleteMany", ctx, models)}
}

func (_c *MockInventoryRepository_DeleteMany_Call) Run(run func(ctx context.Context, models []entity.InventoryEntry)) *MockInventoryRepository_DeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.InventoryEntry))
	})
	return _c
}

func (_c *MockInventoryRepository_DeleteMany_Call) Return(_a0 error) *MockInventoryRepository_DeleteMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInventoryRepository_DeleteMany_Call) RunAndReturn(run func(context.Context, []entity.InventoryEntry) error) *MockInventoryRepository_DeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, spec
func (_m *MockInventoryRepository) FindAll(ctx context.Context, spec crud.Specification[entity.InventoryEntry]) ([]entity.InventoryEntry, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.InventoryEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.InventoryEntry]) ([]entity.InventoryEntry, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.InventoryEntry]) []entity.InventoryEntry); ok {
		r0 = rf(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.InventoryEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, crud.Specification[entity.InventoryEntry]) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockInventoryRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[entity.InventoryEntry]
func (_e *MockInventoryRepository_Expecter) FindAll(ctx interface{}, spec interface{}) *MockInventoryRepository_FindAll_Call {
	return &MockInventoryRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, spec)}
}

func (_c *MockInventoryRepository_FindAll_Call) Run(run func(ctx context.Context, spec crud.Specification[entity.InventoryEntry])) *MockInventoryRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(crud.Specification[entity.InventoryEntry]))
	})
	return _c
}

func (_c *MockInventoryRepository_FindAll_Call) Return(_a0 []entity.InventoryEntry, _a1 error) *MockInventoryRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryRepository_FindAll_Call) RunAndReturn(run func(context.Context, crud.Specification[entity.InventoryEntry]) ([]entity.InventoryEntry, error)) *MockInventoryRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindFirst provides a mock function with given fields: ctx, spec
func (_m *MockInventoryRepository) FindFirst(ctx context.Context, spec crud.Specification[entity.InventoryEntry]) (entity.InventoryEntry, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindFirst")
	}

	var r0 entity.InventoryEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.InventoryEntry]) (entity.InventoryEntry, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.InventoryEntry]) entity.InventoryEntry); ok {
		r0 = rf(ctx, spec)
	} else {
		r0 = ret.Get(0).(entity.InventoryEntry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, crud.Specification[entity.InventoryEntry]) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryRepository_FindFirst_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFirst'
type MockInventoryRepository_FindFirst_Call struct {
	*mock.Call
}

// FindFirst is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[entity.InventoryEntry]
func (_e *MockInventoryRepository_Expecter) FindFirst(ctx interface{}, spec interface{}) *MockInventoryRepository_FindFirst_Call {
	return &MockInventoryRepository_FindFirst_Call{Call: _e.mock.On("FindFirst", ctx, spec)}
}

func (_c *MockInventoryRepository_FindFirst_Call) Run(run func(ctx context.Context, spec crud.Specification[entity.InventoryEntry])) *MockInventoryRepository_FindFirst_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(crud.Specification[entity.InventoryEntry]))
	})
	return _c
}

func (_c *MockInventoryRepository_FindFirst_Call) Return(_a0 entity.InventoryEntry, _a1 error) *MockInventoryRepository_FindFirst_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryRepository_FindFirst_Call) RunAndReturn(run func(context.Context, crud.Specification[entity.InventoryEntry]) (entity.InventoryEntry, error)) *MockInventoryRepository_FindFirst_Call {
	_c.Call.Return(run)
	return _c
}

// GetGormInstance provides a mock function with given fields: ctx
func (_m *MockInventoryRepository) GetGormInstance(ctx context.Context) (*gorm.DB, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGormInstance")
	}

	var r0 *gorm.DB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryRepository_GetGormInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGormInstance'
type MockInventoryRepository_GetGormInstance_Call struct {
	*mock.Call
}

// GetGormInstance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInventoryRepository_Expecter) GetGormInstance(ctx interface{}) *MockInventoryRepository_GetGormInstance_Call {
	return &MockInventoryRepository_GetGormInstance_Call{Call: _e.mock.On("GetGormInstance", ctx)}
}

func (_c *MockInventoryRepository_GetGormInstance_Call) Run(run func(ctx context.Context)) *MockInventoryRepository_GetGormInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInventoryRepository_GetGormInstance_Call) Return(_a0 *gorm.DB, _a1 error) *MockInventoryRepository_GetGormInstance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryRepository_GetGormInstance_Call) RunAndReturn(run func(context.Context) (*gorm.DB, error)) *MockInventoryRepository_GetGormInstance_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, model
func (_m *MockInventoryRepository) Insert(ctx context.Context, model entity.InventoryEntry) (entity.InventoryEntry, error) {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 entity.InventoryEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.InventoryEntry) (entity.InventoryEntry, error)); ok {
		return rf(ctx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.InventoryEntry) entity.InventoryEntry); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Get(0).(entity.InventoryEntry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.InventoryEntry) error); ok {
		r1 = rf(ctx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockInventoryRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - model entity.InventoryEntry
func (_e *MockInventoryRepository_Expecter) Insert(ctx interface{}, model interface{}) *MockInventoryRepository_Insert_Call {
	return &MockInventoryRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, model)}
}

func (_c *MockInventoryRepository_Insert_Call) Run(run func(ctx context.Context, model entity.InventoryEntry)) *MockInventoryRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.InventoryEntry))
	})
	return _c
}

func (_c *MockInventoryRepository_Insert_Call) Return(_a0 entity.InventoryEntry, _a1 error) *MockInventoryRepository_Insert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryRepository_Insert_Call) RunAndReturn(run func(context.Context, entity.InventoryEntry) (entity.InventoryEntry, error)) *MockInventoryRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function with given fields: ctx, models
func (_m *MockInventoryRepository) InsertMany(ctx context.Context, models []entity.InventoryEntry) ([]entity.InventoryEntry, error) {
	ret := _m.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 []entity.InventoryEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.InventoryEntry) ([]entity.InventoryEntry, error)); ok {
		return rf(ctx, models)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []entity.InventoryEntry) []entity.InventoryEntry); ok {
		r0 = rf(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.InventoryEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []entity.InventoryEntry) error); ok {
		r1 = rf(ctx, models)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryRepository_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockInventoryRepository_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []entity.InventoryEntry
func (_e *MockInventoryRepository_Expecter) InsertMany(ctx interface{}, models interface{}) *MockInventoryRepository_InsertMany_Call {
	return &MockInventoryRepository_InsertMany_Call{Call: _e.mock.On("InsertMany", ctx, models)}
}

func (_c *MockInventoryRepository_InsertMany_Call) Run(run func(ctx context.Context, models []entity.InventoryEntry)) *MockInventoryRepository_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.InventoryEntry))
	})
	return _c
}

func (_c *MockInventoryRepository_InsertMany_Call) Return(_a0 []entity.InventoryEntry, _a1 error) *MockInventoryRepository_InsertMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryRepository_InsertMany_Call) RunAndReturn(run func(context.Context, []entity.InventoryEntry) ([]entity.InventoryEntry, error)) *MockInventoryRepository_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// ListHoldings provides a mock function with given fields: ctx, profileID, cardID
func (_m *MockInventoryRepository) ListHoldings(ctx context.Context, profileID uuid.UUID, cardID uuid.UUID) ([]repository.CardHolding, error) {
	ret := _m.Called(ctx, profileID, cardID)

	if len(ret) == 0 {
		panic("no return value specified for ListHoldings")
	}

	var r0 []repository.CardHolding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]repository.CardHolding, error)); ok {
		return rf(ctx, profileID, cardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []repository.CardHolding); ok {
		r0 = rf(ctx, profileID, cardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.CardHolding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, profileID, cardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryRepository_ListHoldings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHoldings'
type MockInventoryRepository_ListHoldings_Call struct {
	*mock.Call
}

// ListHoldings is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uuid.UUID
//   - cardID uuid.UUID
func (_e *MockInventoryRepository_Expecter) ListHoldings(ctx interface{}, profileID interface{}, cardID interface{}) *MockInventoryRepository_ListHoldings_Call {
	return &MockInventoryRepository_ListHoldings_Call{Call: _e.mock.On("ListHoldings", ctx, profileID, cardID)}
}

func (_c *MockInventoryRepository_ListHoldings_Call) Run(run func(ctx context.Context, profileID uuid.UUID, cardID uuid.UUID)) *MockInventoryRepository_ListHoldings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockInventoryRepository_ListHoldings_Call) Return(_a0 []repository.CardHolding, _a1 error) *MockInventoryRepository_ListHoldings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryRepository_ListHoldings_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]repository.CardHolding, error)) *MockInventoryRepository_ListHoldings_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMany provides a mock function with given fields: ctx, models
func (_m *MockInventoryRepository) SaveMany(ctx context.Context, models []entity.InventoryEntry) ([]entity.InventoryEntry, error) {
	ret := _m.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 []entity.InventoryEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.InventoryEntry) ([]entity.InventoryEntry, error)); ok {
		return rf(ctx, models)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []entity.InventoryEntry) []entity.InventoryEntry); ok {
		r0 = rf(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.InventoryEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []entity.InventoryEntry) error); ok {
		r1 = rf(ctx, models)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryRepository_SaveMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMany'
type MockInventoryRepository_SaveMany_Call struct {
	*mock.Call
}

// SaveMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []entity.InventoryEntry
func (_e *MockInventoryRepository_Expecter) SaveMany(ctx interface{}, models interface{}) *MockInventoryRepository_SaveMany_Call {
	return &MockInventoryRepository_SaveMany_Call{Call: _e.mock.On("SaveMany", ctx, models)}
}

func (_c *MockInventoryRepository_SaveMany_Call) Run(run func(ctx context.Context, models []entity.InventoryEntry)) *MockInventoryRepository_SaveMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.InventoryEntry))
	})
	return _c
}

func (_c *MockInventoryRepository_SaveMany_Call) Return(_a0 []entity.InventoryEntry, _a1 error) *MockInventoryRepository_SaveMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryRepository_SaveMany_Call) RunAndReturn(run func(context.Context, []entity.InventoryEntry) ([]entity.InventoryEntry, error)) *MockInventoryRepository_SaveMany_Call {
	_c.Call.Return(run)
	return _c
}

// SumQuantity provides a mock function with given fields: ctx, collectionID
func (_m *MockInventoryRepository) SumQuantity(ctx context.Context, collectionID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, collectionID)

	if len(ret) == 0 {
		panic("no return value specified for SumQuantity")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, collectionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, collectionID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, collectionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryRepository_SumQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumQuantity'
type MockInventoryRepository_SumQuantity_Call struct {
	*mock.Call
}

// SumQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - collectionID uuid.UUID
func (_e *MockInventoryRepository_Expecter) SumQuantity(ctx interface{}, collectionID interface{}) *MockInventoryRepository_SumQuantity_Call {
	return &MockInventoryRepository_SumQuantity_Call{Call: _e.mock.On("SumQuantity", ctx, collectionID)}
}

func (_c *MockInventoryRepository_SumQuantity_Call) Run(run func(ctx context.Context, collectionID uuid.UUID)) *MockInventoryRepository_SumQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockInventoryRepository_SumQuantity_Call) Return(_a0 int, _a1 error) *MockInventoryRepository_SumQuantity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryRepository_SumQuantity_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockInventoryRepository_SumQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, model
func (_m *MockInventoryRepository) Update(ctx context.Context, model entity.InventoryEntry) (entity.InventoryEntry, error) {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.InventoryEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.InventoryEntry) (entity.InventoryEntry, error)); ok {
		return rf(ctx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.InventoryEntry) entity.InventoryEntry); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Get(0).(entity.InventoryEntry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.InventoryEntry) error); ok {
		r1 = rf(ctx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockInventoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - model entity.InventoryEntry
func (_e *MockInventoryRepository_Expecter) Update(ctx interface{}, model interface{}) *MockInventoryRepository_Update_Call {
	return &MockInventoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, model)}
}

func (_c *MockInventoryRepository_Update_Call) Run(run func(ctx context.Context, model entity.InventoryEntry)) *MockInventoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.InventoryEntry))
	})
	return _c
}

func (_c *MockInventoryRepository_Update_Call) Return(_a0 entity.InventoryEntry, _a1 error) *MockInventoryRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryRepository_Update_Call) RunAndReturn(run func(context.Context, entity.InventoryEntry) (entity.InventoryEntry, error)) *MockInventoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInventoryRepository creates a new instance of MockInventoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryRepository {
	mock := &MockInventoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
