// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	clerk "github.com/clerk/clerk-sdk-go/v2"

	mock "github.com/stretchr/testify/mock"
)

// MockKeySource is an autogenerated mock type for the KeySource type
type MockKeySource struct {
	mock.Mock
}

type MockKeySource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeySource) EXPECT() *MockKeySource_Expecter {
	return &MockKeySource_Expecter{mock: &_m.Mock}
}

// FindKey provides a mock function with given fields: ctx, keyID
func (_m *MockKeySource) FindKey(ctx context.Context, keyID string) (*clerk.JSONWebKey, error) {
	ret := _m.Called(ctx, keyID)

	if len(ret) == 0 {
		panic("no return value specified for FindKey")
	}

	var r0 *clerk.JSONWebKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*clerk.JSONWebKey, error)); ok {
		return rf(ctx, keyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *clerk.JSONWebKey); ok {
		r0 = rf(ctx, keyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clerk.JSONWebKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, keyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeySource_FindKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindKey'
type MockKeySource_FindKey_Call struct {
	*mock.Call
}

// FindKey is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
func (_e *MockKeySource_Expecter) FindKey(ctx interface{}, keyID interface{}) *MockKeySource_FindKey_Call {
	return &MockKeySource_FindKey_Call{Call: _e.mock.On("FindKey", ctx, keyID)}
}

func (_c *MockKeySource_FindKey_Call) Run(run func(ctx context.Context, keyID string)) *MockKeySource_FindKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockKeySource_FindKey_Call) Return(_a0 *clerk.JSONWebKey, _a1 error) *MockKeySource_FindKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeySource_FindKey_Call) RunAndReturn(run func(context.Context, string) (*clerk.JSONWebKey, error)) *MockKeySource_FindKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKeySource creates a new instance of MockKeySource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeySource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeySource {
	mock := &MockKeySource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
