// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/itsLeonB/cardstack/backend/internal/domain/repository"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMatchRepository is an autogenerated mock type for the MatchRepository type
type MockMatchRepository struct {
	mock.Mock
}

type MockMatchRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchRepository) EXPECT() *MockMatchRepository_Expecter {
	return &MockMatchRepository_Expecter{mock: &_m.Mock}
}

// CardsByIDs provides a mock function with given fields: ctx, ids
func (_m *MockMatchRepository) CardsByIDs(ctx context.Context, ids []uuid.UUID) ([]repository.CardResult, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for CardsByIDs")
	}

	var r0 []repository.CardResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]repository.CardResult, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []repository.CardResult); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.CardResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchRepository_CardsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CardsByIDs'
type MockMatchRepository_CardsByIDs_Call struct {
	*mock.Call
}

// CardsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockMatchRepository_Expecter) CardsByIDs(ctx interface{}, ids interface{}) *MockMatchRepository_CardsByIDs_Call {
	return &MockMatchRepository_CardsByIDs_Call{Call: _e.mock.On("CardsByIDs", ctx, ids)}
}

func (_c *MockMatchRepository_CardsByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockMatchRepository_CardsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockMatchRepository_CardsByIDs_Call) Return(_a0 []repository.CardResult, _a1 error) *MockMatchRepository_CardsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchRepository_CardsByIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]repository.CardResult, error)) *MockMatchRepository_CardsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatchRepository creates a new instance of MockMatchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchRepository {
	mock := &MockMatchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
