// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/itsLeonB/cardstack/backend/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockMatchService is an autogenerated mock type for the MatchService type
type MockMatchService struct {
	mock.Mock
}

type MockMatchService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchService) EXPECT() *MockMatchService_Expecter {
	return &MockMatchService_Expecter{mock: &_m.Mock}
}

// Match provides a mock function with given fields: ctx, req
func (_m *MockMatchService) Match(ctx context.Context, req dto.MatchRequest) (dto.MatchResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Match")
	}

	var r0 dto.MatchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.MatchRequest) (dto.MatchResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.MatchRequest) dto.MatchResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.MatchResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.MatchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchService_Match_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Match'
type MockMatchService_Match_Call struct {
	*mock.Call
}

// Match is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.MatchRequest
func (_e *MockMatchService_Expecter) Match(ctx interface{}, req interface{}) *MockMatchService_Match_Call {
	return &MockMatchService_Match_Call{Call: _e.mock.On("Match", ctx, req)}
}

func (_c *MockMatchService_Match_Call) Run(run func(ctx context.Context, req dto.MatchRequest)) *MockMatchService_Match_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.MatchRequest))
	})
	return _c
}

func (_c *MockMatchService_Match_Call) Return(_a0 dto.MatchResult, _a1 error) *MockMatchService_Match_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchService_Match_Call) RunAndReturn(run func(context.Context, dto.MatchRequest) (dto.MatchResult, error)) *MockMatchService_Match_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatchService creates a new instance of MockMatchService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchService {
	mock := &MockMatchService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
