// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/itsLeonB/cardstack/backend/internal/domain/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockMatchRepository is an autogenerated mock type for the MatchRepository type
type MockMatchRepository struct {
	mock.Mock
}

type MockMatchRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchRepository) EXPECT() *MockMatchRepository_Expecter {
	return &MockMatchRepository_Expecter{mock: &_m.Mock}
}

// RandomCards provides a mock function with given fields: ctx, limit
func (_m *MockMatchRepository) RandomCards(ctx context.Context, limit int) ([]repository.CardResult, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for RandomCards")
	}

	var r0 []repository.CardResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]repository.CardResult, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []repository.CardResult); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.CardResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchRepository_RandomCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RandomCards'
type MockMatchRepository_RandomCards_Call struct {
	*mock.Call
}

// RandomCards is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockMatchRepository_Expecter) RandomCards(ctx interface{}, limit interface{}) *MockMatchRepository_RandomCards_Call {
	return &MockMatchRepository_RandomCards_Call{Call: _e.mock.On("RandomCards", ctx, limit)}
}

func (_c *MockMatchRepository_RandomCards_Call) Run(run func(ctx context.Context, limit int)) *MockMatchRepository_RandomCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockMatchRepository_RandomCards_Call) Return(_a0 []repository.CardResult, _a1 error) *MockMatchRepository_RandomCards_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchRepository_RandomCards_Call) RunAndReturn(run func(context.Context, int) ([]repository.CardResult, error)) *MockMatchRepository_RandomCards_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatchRepository creates a new instance of MockMatchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchRepository {
	mock := &MockMatchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
