// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockObjectStore is an autogenerated mock type for the ObjectStore type
type MockObjectStore struct {
	mock.Mock
}

type MockObjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStore) EXPECT() *MockObjectStore_Expecter {
	return &MockObjectStore_Expecter{mock: &_m.Mock}
}

// Put provides a mock function with given fields: ctx, key, contentType, body
func (_m *MockObjectStore) Put(ctx context.Context, key string, contentType string, body []byte) error {
	ret := _m.Called(ctx, key, contentType, body)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = rf(ctx, key, contentType, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockObjectStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockObjectStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - contentType string
//   - body []byte
func (_e *MockObjectStore_Expecter) Put(ctx interface{}, key interface{}, contentType interface{}, body interface{}) *MockObjectStore_Put_Call {
	return &MockObjectStore_Put_Call{Call: _e.mock.On("Put", ctx, key, contentType, body)}
}

func (_c *MockObjectStore_Put_Call) Run(run func(ctx context.Context, key string, contentType string, body []byte)) *MockObjectStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *MockObjectStore_Put_Call) Return(_a0 error) *MockObjectStore_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObjectStore_Put_Call) RunAndReturn(run func(context.Context, string, string, []byte) error) *MockObjectStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObjectStore creates a new instance of MockObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStore {
	mock := &MockObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
