// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	crud "github.com/itsLeonB/go-crud"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository[T any] struct {
	mock.Mock
}

type MockRepository_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockRepository[T]) EXPECT() *MockRepository_Expecter[T] {
	return &MockRepository_Expecter[T]{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, model
func (_m *MockRepository[T]) Delete(ctx context.Context, model T) error {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call[T any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - model T
func (_e *MockRepository_Expecter[T]) Delete(ctx interface{}, model interface{}) *MockRepository_Delete_Call[T] {
	return &MockRepository_Delete_Call[T]{Call: _e.mock.On("Delete", ctx, model)}
}

func (_c *MockRepository_Delete_Call[T]) Run(run func(ctx context.Context, model T)) *MockRepository_Delete_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *MockRepository_Delete_Call[T]) Return(_a0 error) *MockRepository_Delete_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call[T]) RunAndReturn(run func(context.Context, T) error) *MockRepository_Delete_Call[T] {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function with given fields: ctx, models
func (_m *MockRepository[T]) DeleteMany(ctx context.Context, models []T) error {
	ret := _m.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []T) error); ok {
		r0 = rf(ctx, models)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type MockRepository_DeleteMany_Call[T any] struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []T
func (_e *MockRepository_Expecter[T]) DeleteMany(ctx interface{}, models interface{}) *MockRepository_DeleteMany_Call[T] {
	return &MockRepository_DeleteMany_Call[T]{Call: _e.mock.On("DeleteMany", ctx, models)}
}

func (_c *MockRepository_DeleteMany_Call[T]) Run(run func(ctx context.Context, models []T)) *MockRepository_DeleteMany_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]T))
	})
	return _c
}

func (_c *MockRepository_DeleteMany_Call[T]) Return(_a0 error) *MockRepository_DeleteMany_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteMany_Call[T]) RunAndReturn(run func(context.Context, []T) error) *MockRepository_DeleteMany_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, spec
func (_m *MockRepository[T]) FindAll(ctx context.Context, spec crud.Specification[T]) ([]T, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[T]) ([]T, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[T]) []T); ok {
		r0 = rf(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, crud.Specification[T]) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRepository_FindAll_Call[T any] struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[T]
func (_e *MockRepository_Expecter[T]) FindAll(ctx interface{}, spec interface{}) *MockRepository_FindAll_Call[T] {
	return &MockRepository_FindAll_Call[T]{Call: _e.mock.On("FindAll", ctx, spec)}
}

func (_c *MockRepository_FindAll_Call[T]) Run(run func(ctx context.Context, spec crud.Specification[T])) *MockRepository_FindAll_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(crud.Specification[T]))
	})
	return _c
}

func (_c *MockRepository_FindAll_Call[T]) Return(_a0 []T, _a1 error) *MockRepository_FindAll_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindAll_Call[T]) RunAndReturn(run func(context.Context, crud.Specification[T]) ([]T, error)) *MockRepository_FindAll_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FindFirst provides a mock function with given fields: ctx, spec
func (_m *MockRepository[T]) FindFirst(ctx context.Context, spec crud.Specification[T]) (T, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindFirst")
	}

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[T]) (T, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[T]) T); ok {
		r0 = rf(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, crud.Specification[T]) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindFirst_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFirst'
type MockRepository_FindFirst_Call[T any] struct {
	*mock.Call
}

// FindFirst is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[T]
func (_e *MockRepository_Expecter[T]) FindFirst(ctx interface{}, spec interface{}) *MockRepository_FindFirst_Call[T] {
	return &MockRepository_FindFirst_Call[T]{Call: _e.mock.On("FindFirst", ctx, spec)}
}

func (_c *MockRepository_FindFirst_Call[T]) Run(run func(ctx context.Context, spec crud.Specification[T])) *MockRepository_FindFirst_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(crud.Specification[T]))
	})
	return _c
}

func (_c *MockRepository_FindFirst_Call[T]) Return(_a0 T, _a1 error) *MockRepository_FindFirst_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindFirst_Call[T]) RunAndReturn(run func(context.Context, crud.Specification[T]) (T, error)) *MockRepository_FindFirst_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetGormInstance provides a mock function with given fields: ctx
func (_m *MockRepository[T]) GetGormInstance(ctx context.Context) (*gorm.DB, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGormInstance")
	}

	var r0 *gorm.DB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetGormInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGormInstance'
type MockRepository_GetGormInstance_Call[T any] struct {
	*mock.Call
}

// GetGormInstance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter[T]) GetGormInstance(ctx interface{}) *MockRepository_GetGormInstance_Call[T] {
	return &MockRepository_GetGormInstance_Call[T]{Call: _e.mock.On("GetGormInstance", ctx)}
}

func (_c *MockRepository_GetGormInstance_Call[T]) Run(run func(ctx context.Context)) *MockRepository_GetGormInstance_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetGormInstance_Call[T]) Return(_a0 *gorm.DB, _a1 error) *MockRepository_GetGormInstance_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetGormInstance_Call[T]) RunAndReturn(run func(context.Context) (*gorm.DB, error)) *MockRepository_GetGormInstance_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, model
func (_m *MockRepository[T]) Insert(ctx context.Context, model T) (T, error) {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, T) (T, error)); ok {
		return rf(ctx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, T) T); ok {
		r0 = rf(ctx, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = rf(ctx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockRepository_Insert_Call[T any] struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - model T
func (_e *MockRepository_Expecter[T]) Insert(ctx interface{}, model interface{}) *MockRepository_Insert_Call[T] {
	return &MockRepository_Insert_Call[T]{Call: _e.mock.On("Insert", ctx, model)}
}

func (_c *MockRepository_Insert_Call[T]) Run(run func(ctx context.Context, model T)) *MockRepository_Insert_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *MockRepository_Insert_Call[T]) Return(_a0 T, _a1 error) *MockRepository_Insert_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Insert_Call[T]) RunAndReturn(run func(context.Context, T) (T, error)) *MockRepository_Insert_Call[T] {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function with given fields: ctx, models
func (_m *MockRepository[T]) InsertMany(ctx context.Context, models []T) ([]T, error) {
	ret := _m.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 []T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []T) ([]T, error)); ok {
		return rf(ctx, models)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []T) []T); ok {
		r0 = rf(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []T) error); ok {
		r1 = rf(ctx, models)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockRepository_InsertMany_Call[T any] struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []T
func (_e *MockRepository_Expecter[T]) InsertMany(ctx interface{}, models interface{}) *MockRepository_InsertMany_Call[T] {
	return &MockRepository_InsertMany_Call[T]{Call: _e.mock.On("InsertMany", ctx, models)}
}

func (_c *MockRepository_InsertMany_Call[T]) Run(run func(ctx context.Context, models []T)) *MockRepository_InsertMany_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]T))
	})
	return _c
}

func (_c *MockRepository_InsertMany_Call[T]) Return(_a0 []T, _a1 error) *MockRepository_InsertMany_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_InsertMany_Call[T]) RunAndReturn(run func(context.Context, []T) ([]T, error)) *MockRepository_InsertMany_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SaveMany provides a mock function with given fields: ctx, models
func (_m *MockRepository[T]) SaveMany(ctx context.Context, models []T) ([]T, error) {
	ret := _m.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 []T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []T) ([]T, error)); ok {
		return rf(ctx, models)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []T) []T); ok {
		r0 = rf(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []T) error); ok {
		r1 = rf(ctx, models)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_SaveMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMany'
type MockRepository_SaveMany_Call[T any] struct {
	*mock.Call
}

// SaveMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []T
func (_e *MockRepository_Expecter[T]) SaveMany(ctx interface{}, models interface{}) *MockRepository_SaveMany_Call[T] {
	return &MockRepository_SaveMany_Call[T]{Call: _e.mock.On("SaveMany", ctx, models)}
}

func (_c *MockRepository_SaveMany_Call[T]) Run(run func(ctx context.Context, models []T)) *MockRepository_SaveMany_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]T))
	})
	return _c
}

func (_c *MockRepository_SaveMany_Call[T]) Return(_a0 []T, _a1 error) *MockRepository_SaveMany_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_SaveMany_Call[T]) RunAndReturn(run func(context.Context, []T) ([]T, error)) *MockRepository_SaveMany_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, model
func (_m *MockRepository[T]) Update(ctx context.Context, model T) (T, error) {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, T) (T, error)); ok {
		return rf(ctx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, T) T); ok {
		r0 = rf(ctx, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = rf(ctx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call[T any] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - model T
func (_e *MockRepository_Expecter[T]) Update(ctx interface{}, model interface{}) *MockRepository_Update_Call[T] {
	return &MockRepository_Update_Call[T]{Call: _e.mock.On("Update", ctx, model)}
}

func (_c *MockRepository_Update_Call[T]) Run(run func(ctx context.Context, model T)) *MockRepository_Update_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *MockRepository_Update_Call[T]) Return(_a0 T, _a1 error) *MockRepository_Update_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Update_Call[T]) RunAndReturn(run func(context.Context, T) (T, error)) *MockRepository_Update_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository[T] {
	mock := &MockRepository[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
