// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/itsLeonB/cardstack/backend/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenVerifier is an autogenerated mock type for the TokenVerifier type
type MockTokenVerifier struct {
	mock.Mock
}

type MockTokenVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenVerifier) EXPECT() *MockTokenVerifier_Expecter {
	return &MockTokenVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: ctx, token
func (_m *MockTokenVerifier) Verify(ctx context.Context, token string) (dto.AuthIdentity, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 dto.AuthIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dto.AuthIdentity, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dto.AuthIdentity); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(dto.AuthIdentity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockTokenVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenVerifier_Expecter) Verify(ctx interface{}, token interface{}) *MockTokenVerifier_Verify_Call {
	return &MockTokenVerifier_Verify_Call{Call: _e.mock.On("Verify", ctx, token)}
}

func (_c *MockTokenVerifier_Verify_Call) Run(run func(ctx context.Context, token string)) *MockTokenVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenVerifier_Verify_Call) Return(_a0 dto.AuthIdentity, _a1 error) *MockTokenVerifier_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenVerifier_Verify_Call) RunAndReturn(run func(context.Context, string) (dto.AuthIdentity, error)) *MockTokenVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenVerifier creates a new instance of MockTokenVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenVerifier {
	mock := &MockTokenVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
