// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/itsLeonB/cardstack/backend/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// ResolveCaller provides a mock function with given fields: ctx, identity
func (_m *MockUserService) ResolveCaller(ctx context.Context, identity dto.AuthIdentity) (dto.CallerIdentity, error) {
	ret := _m.Called(ctx, identity)

	if len(ret) == 0 {
		panic("no return value specified for ResolveCaller")
	}

	var r0 dto.CallerIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.AuthIdentity) (dto.CallerIdentity, error)); ok {
		return rf(ctx, identity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.AuthIdentity) dto.CallerIdentity); ok {
		r0 = rf(ctx, identity)
	} else {
		r0 = ret.Get(0).(dto.CallerIdentity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.AuthIdentity) error); ok {
		r1 = rf(ctx, identity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_ResolveCaller_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveCaller'
type MockUserService_ResolveCaller_Call struct {
	*mock.Call
}

// ResolveCaller is a helper method to define mock.On call
//   - ctx context.Context
//   - identity dto.AuthIdentity
func (_e *MockUserService_Expecter) ResolveCaller(ctx interface{}, identity interface{}) *MockUserService_ResolveCaller_Call {
	return &MockUserService_ResolveCaller_Call{Call: _e.mock.On("ResolveCaller", ctx, identity)}
}

func (_c *MockUserService_ResolveCaller_Call) Run(run func(ctx context.Context, identity dto.AuthIdentity)) *MockUserService_ResolveCaller_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.AuthIdentity))
	})
	return _c
}

func (_c *MockUserService_ResolveCaller_Call) Return(_a0 dto.CallerIdentity, _a1 error) *MockUserService_ResolveCaller_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_ResolveCaller_Call) RunAndReturn(run func(context.Context, dto.AuthIdentity) (dto.CallerIdentity, error)) *MockUserService_ResolveCaller_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
