// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/itsLeonB/cardstack/backend/internal/domain/entity"
	crud "github.com/itsLeonB/go-crud"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, model
func (_m *MockUserRepository) Delete(ctx context.Context, model entity.User) error {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) error); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - model entity.User
func (_e *MockUserRepository_Expecter) Delete(ctx interface{}, model interface{}) *MockUserRepository_Delete_Call {
	return &MockUserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, model)}
}

func (_c *MockUserRepository_Delete_Call) Run(run func(ctx context.Context, model entity.User)) *MockUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.User))
	})
	return _c
}

func (_c *MockUserRepository_Delete_Call) Return(_a0 error) *MockUserRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Delete_Call) RunAndReturn(run func(context.Context, entity.User) error) *MockUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function with given fields: ctx, models
func (_m *MockUserRepository) DeleteMany(ctx context.Context, models []entity.User) error {
	ret := _m.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.User) error); ok {
		r0 = rf(ctx, models)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type MockUserRepository_DeleteMany_Call struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []entity.User
func (_e *MockUserRepository_Expecter) DeleteMany(ctx interface{}, models interface{}) *MockUserRepository_DeleteMany_Call {
	return &MockUserRepository_DeleteMany_Call{Call: _e.mock.On("DeleteMany", ctx, models)}
}

func (_c *MockUserRepository_DeleteMany_Call) Run(run func(ctx context.Context, models []entity.User)) *MockUserRepository_DeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.User))
	})
	return _c
}

func (_c *MockUserRepository_DeleteMany_Call) Return(_a0 error) *MockUserRepository_DeleteMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_DeleteMany_Call) RunAndReturn(run func(context.Context, []entity.User) error) *MockUserRepository_DeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, spec
func (_m *MockUserRepository) FindAll(ctx context.Context, spec crud.Specification[entity.User]) ([]entity.User, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.User]) ([]entity.User, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.User]) []entity.User); ok {
		r0 = rf(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, crud.Specification[entity.User]) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockUserRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[entity.User]
func (_e *MockUserRepository_Expecter) FindAll(ctx interface{}, spec interface{}) *MockUserRepository_FindAll_Call {
	return &MockUserRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, spec)}
}

func (_c *MockUserRepository_FindAll_Call) Run(run func(ctx context.Context, spec crud.Specification[entity.User])) *MockUserRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(crud.Specification[entity.User]))
	})
	return _c
}

func (_c *MockUserRepository_FindAll_Call) Return(_a0 []entity.User, _a1 error) *MockUserRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindAll_Call) RunAndReturn(run func(context.Context, crud.Specification[entity.User]) ([]entity.User, error)) *MockUserRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindFirst provides a mock function with given fields: ctx, spec
func (_m *MockUserRepository) FindFirst(ctx context.Context, spec crud.Specification[entity.User]) (entity.User, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindFirst")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.User]) (entity.User, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.User]) entity.User); ok {
		r0 = rf(ctx, spec)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, crud.Specification[entity.User]) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindFirst_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFirst'
type MockUserRepository_FindFirst_Call struct {
	*mock.Call
}

// FindFirst is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[entity.User]
func (_e *MockUserRepository_Expecter) FindFirst(ctx interface{}, spec interface{}) *MockUserRepository_FindFirst_Call {
	return &MockUserRepository_FindFirst_Call{Call: _e.mock.On("FindFirst", ctx, spec)}
}

func (_c *MockUserRepository_FindFirst_Call) Run(run func(ctx context.Context, spec crud.Specification[entity.User])) *MockUserRepository_FindFirst_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(crud.Specification[entity.User]))
	})
	return _c
}

func (_c *MockUserRepository_FindFirst_Call) Return(_a0 entity.User, _a1 error) *MockUserRepository_FindFirst_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindFirst_Call) RunAndReturn(run func(context.Context, crud.Specification[entity.User]) (entity.User, error)) *MockUserRepository_FindFirst_Call {
	_c.Call.Return(run)
	return _c
}

// GetGormInstance provides a mock function with given fields: ctx
func (_m *MockUserRepository) GetGormInstance(ctx context.Context) (*gorm.DB, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGormInstance")
	}

	var r0 *gorm.DB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetGormInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGormInstance'
type MockUserRepository_GetGormInstance_Call struct {
	*mock.Call
}

// GetGormInstance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserRepository_Expecter) GetGormInstance(ctx interface{}) *MockUserRepository_GetGormInstance_Call {
	return &MockUserRepository_GetGormInstance_Call{Call: _e.mock.On("GetGormInstance", ctx)}
}

func (_c *MockUserRepository_GetGormInstance_Call) Run(run func(ctx context.Context)) *MockUserRepository_GetGormInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserRepository_GetGormInstance_Call) Return(_a0 *gorm.DB, _a1 error) *MockUserRepository_GetGormInstance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetGormInstance_Call) RunAndReturn(run func(context.Context) (*gorm.DB, error)) *MockUserRepository_GetGormInstance_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, model
func (_m *MockUserRepository) Insert(ctx context.Context, model entity.User) (entity.User, error) {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) (entity.User, error)); ok {
		return rf(ctx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) entity.User); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.User) error); ok {
		r1 = rf(ctx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockUserRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - model entity.User
func (_e *MockUserRepository_Expecter) Insert(ctx interface{}, model interface{}) *MockUserRepository_Insert_Call {
	return &MockUserRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, model)}
}

func (_c *MockUserRepository_Insert_Call) Run(run func(ctx context.Context, model entity.User)) *MockUserRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.User))
	})
	return _c
}

func (_c *MockUserRepository_Insert_Call) Return(_a0 entity.User, _a1 error) *MockUserRepository_Insert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_Insert_Call) RunAndReturn(run func(context.Context, entity.User) (entity.User, error)) *MockUserRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function with given fields: ctx, models
func (_m *MockUserRepository) InsertMany(ctx context.Context, models []entity.User) ([]entity.User, error) {
	ret := _m.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 []entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.User) ([]entity.User, error)); ok {
		return rf(ctx, models)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []entity.User) []entity.User); ok {
		r0 = rf(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []entity.User) error); ok {
		r1 = rf(ctx, models)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockUserRepository_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []entity.User
func (_e *MockUserRepository_Expecter) InsertMany(ctx interface{}, models interface{}) *MockUserRepository_InsertMany_Call {
	return &MockUserRepository_InsertMany_Call{Call: _e.mock.On("InsertMany", ctx, models)}
}

func (_c *MockUserRepository_InsertMany_Call) Run(run func(ctx context.Context, models []entity.User)) *MockUserRepository_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.User))
	})
	return _c
}

func (_c *MockUserRepository_InsertMany_Call) Return(_a0 []entity.User, _a1 error) *MockUserRepository_InsertMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_InsertMany_Call) RunAndReturn(run func(context.Context, []entity.User) ([]entity.User, error)) *MockUserRepository_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// LockIdentity provides a mock function with given fields: ctx, provider, subject
func (_m *MockUserRepository) LockIdentity(ctx context.Context, provider string, subject string) error {
	ret := _m.Called(ctx, provider, subject)

	if len(ret) == 0 {
		panic("no return value specified for LockIdentity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, provider, subject)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_LockIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockIdentity'
type MockUserRepository_LockIdentity_Call struct {
	*mock.Call
}

// LockIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - subject string
func (_e *MockUserRepository_Expecter) LockIdentity(ctx interface{}, provider interface{}, subject interface{}) *MockUserRepository_LockIdentity_Call {
	return &MockUserRepository_LockIdentity_Call{Call: _e.mock.On("LockIdentity", ctx, provider, subject)}
}

func (_c *MockUserRepository_LockIdentity_Call) Run(run func(ctx context.Context, provider string, subject string)) *MockUserRepository_LockIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_LockIdentity_Call) Return(_a0 error) *MockUserRepository_LockIdentity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_LockIdentity_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserRepository_LockIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMany provides a mock function with given fields: ctx, models
func (_m *MockUserRepository) SaveMany(ctx context.Context, models []entity.User) ([]entity.User, error) {
	ret := _m.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 []entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.User) ([]entity.User, error)); ok {
		return rf(ctx, models)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []entity.User) []entity.User); ok {
		r0 = rf(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []entity.User) error); ok {
		r1 = rf(ctx, models)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_SaveMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMany'
type MockUserRepository_SaveMany_Call struct {
	*mock.Call
}

// SaveMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []entity.User
func (_e *MockUserRepository_Expecter) SaveMany(ctx interface{}, models interface{}) *MockUserRepository_SaveMany_Call {
	return &MockUserRepository_SaveMany_Call{Call: _e.mock.On("SaveMany", ctx, models)}
}

func (_c *MockUserRepository_SaveMany_Call) Run(run func(ctx context.Context, models []entity.User)) *MockUserRepository_SaveMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.User))
	})
	return _c
}

func (_c *MockUserRepository_SaveMany_Call) Return(_a0 []entity.User, _a1 error) *MockUserRepository_SaveMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_SaveMany_Call) RunAndReturn(run func(context.Context, []entity.User) ([]entity.User, error)) *MockUserRepository_SaveMany_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, model
func (_m *MockUserRepository) Update(ctx context.Context, model entity.User) (entity.User, error) {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) (entity.User, error)); ok {
		return rf(ctx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) entity.User); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.User) error); ok {
		r1 = rf(ctx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - model entity.User
func (_e *MockUserRepository_Expecter) Update(ctx interface{}, model interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, model)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(ctx context.Context, model entity.User)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.User))
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(_a0 entity.User, _a1 error) *MockUserRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(context.Context, entity.User) (entity.User, error)) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
