// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/itsLeonB/cardstack/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/itsLeonB/cardstack/backend/internal/adapters/repository"

	uuid "github.com/google/uuid"
)

// MockCatalogRepository is an autogenerated mock type for the CatalogRepository type
type MockCatalogRepository struct {
	mock.Mock
}

type MockCatalogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogRepository) EXPECT() *MockCatalogRepository_Expecter {
	return &MockCatalogRepository_Expecter{mock: &_m.Mock}
}

// ListDistinctCategories provides a mock function with given fields: ctx
func (_m *MockCatalogRepository) ListDistinctCategories(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListDistinctCategories")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_ListDistinctCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDistinctCategories'
type MockCatalogRepository_ListDistinctCategories_Call struct {
	*mock.Call
}

// ListDistinctCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCatalogRepository_Expecter) ListDistinctCategories(ctx interface{}) *MockCatalogRepository_ListDistinctCategories_Call {
	return &MockCatalogRepository_ListDistinctCategories_Call{Call: _e.mock.On("ListDistinctCategories", ctx)}
}

func (_c *MockCatalogRepository_ListDistinctCategories_Call) Run(run func(ctx context.Context)) *MockCatalogRepository_ListDistinctCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCatalogRepository_ListDistinctCategories_Call) Return(_a0 []string, _a1 error) *MockCatalogRepository_ListDistinctCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_ListDistinctCategories_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockCatalogRepository_ListDistinctCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ListDistinctTags provides a mock function with given fields: ctx
func (_m *MockCatalogRepository) ListDistinctTags(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListDistinctTags")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_ListDistinctTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDistinctTags'
type MockCatalogRepository_ListDistinctTags_Call struct {
	*mock.Call
}

// ListDistinctTags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCatalogRepository_Expecter) ListDistinctTags(ctx interface{}) *MockCatalogRepository_ListDistinctTags_Call {
	return &MockCatalogRepository_ListDistinctTags_Call{Call: _e.mock.On("ListDistinctTags", ctx)}
}

func (_c *MockCatalogRepository_ListDistinctTags_Call) Run(run func(ctx context.Context)) *MockCatalogRepository_ListDistinctTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCatalogRepository_ListDistinctTags_Call) Return(_a0 []string, _a1 error) *MockCatalogRepository_ListDistinctTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_ListDistinctTags_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockCatalogRepository_ListDistinctTags_Call {
	_c.Call.Return(run)
	return _c
}

// ListExpansionSets provides a mock function with given fields: ctx, seriesIDs
func (_m *MockCatalogRepository) ListExpansionSets(ctx context.Context, seriesIDs []uuid.UUID) ([]entity.ExpansionSet, error) {
	ret := _m.Called(ctx, seriesIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListExpansionSets")
	}

	var r0 []entity.ExpansionSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]entity.ExpansionSet, error)); ok {
		return rf(ctx, seriesIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []entity.ExpansionSet); ok {
		r0 = rf(ctx, seriesIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ExpansionSet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, seriesIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_ListExpansionSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExpansionSets'
type MockCatalogRepository_ListExpansionSets_Call struct {
	*mock.Call
}

// ListExpansionSets is a helper method to define mock.On call
//   - ctx context.Context
//   - seriesIDs []uuid.UUID
func (_e *MockCatalogRepository_Expecter) ListExpansionSets(ctx interface{}, seriesIDs interface{}) *MockCatalogRepository_ListExpansionSets_Call {
	return &MockCatalogRepository_ListExpansionSets_Call{Call: _e.mock.On("ListExpansionSets", ctx, seriesIDs)}
}

func (_c *MockCatalogRepository_ListExpansionSets_Call) Run(run func(ctx context.Context, seriesIDs []uuid.UUID)) *MockCatalogRepository_ListExpansionSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockCatalogRepository_ListExpansionSets_Call) Return(_a0 []entity.ExpansionSet, _a1 error) *MockCatalogRepository_ListExpansionSets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_ListExpansionSets_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]entity.ExpansionSet, error)) *MockCatalogRepository_ListExpansionSets_Call {
	_c.Call.Return(run)
	return _c
}

// ListRarities provides a mock function with given fields: ctx
func (_m *MockCatalogRepository) ListRarities(ctx context.Context) ([]entity.Rarity, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRarities")
	}

	var r0 []entity.Rarity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Rarity, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Rarity); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Rarity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_ListRarities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRarities'
type MockCatalogRepository_ListRarities_Call struct {
	*mock.Call
}

// ListRarities is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCatalogRepository_Expecter) ListRarities(ctx interface{}) *MockCatalogRepository_ListRarities_Call {
	return &MockCatalogRepository_ListRarities_Call{Call: _e.mock.On("ListRarities", ctx)}
}

func (_c *MockCatalogRepository_ListRarities_Call) Run(run func(ctx context.Context)) *MockCatalogRepository_ListRarities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCatalogRepository_ListRarities_Call) Return(_a0 []entity.Rarity, _a1 error) *MockCatalogRepository_ListRarities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_ListRarities_Call) RunAndReturn(run func(context.Context) ([]entity.Rarity, error)) *MockCatalogRepository_ListRarities_Call {
	_c.Call.Return(run)
	return _c
}

// ListSeries provides a mock function with given fields: ctx
func (_m *MockCatalogRepository) ListSeries(ctx context.Context) ([]entity.Series, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSeries")
	}

	var r0 []entity.Series
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Series, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Series); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Series)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_ListSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSeries'
type MockCatalogRepository_ListSeries_Call struct {
	*mock.Call
}

// ListSeries is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCatalogRepository_Expecter) ListSeries(ctx interface{}) *MockCatalogRepository_ListSeries_Call {
	return &MockCatalogRepository_ListSeries_Call{Call: _e.mock.On("ListSeries", ctx)}
}

func (_c *MockCatalogRepository_ListSeries_Call) Run(run func(ctx context.Context)) *MockCatalogRepository_ListSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCatalogRepository_ListSeries_Call) Return(_a0 []entity.Series, _a1 error) *MockCatalogRepository_ListSeries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_ListSeries_Call) RunAndReturn(run func(context.Context) ([]entity.Series, error)) *MockCatalogRepository_ListSeries_Call {
	_c.Call.Return(run)
	return _c
}

// ListUngroupedExpansionSets provides a mock function with given fields: ctx
func (_m *MockCatalogRepository) ListUngroupedExpansionSets(ctx context.Context) ([]entity.ExpansionSet, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUngroupedExpansionSets")
	}

	var r0 []entity.ExpansionSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.ExpansionSet, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.ExpansionSet); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ExpansionSet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_ListUngroupedExpansionSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUngroupedExpansionSets'
type MockCatalogRepository_ListUngroupedExpansionSets_Call struct {
	*mock.Call
}

// ListUngroupedExpansionSets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCatalogRepository_Expecter) ListUngroupedExpansionSets(ctx interface{}) *MockCatalogRepository_ListUngroupedExpansionSets_Call {
	return &MockCatalogRepository_ListUngroupedExpansionSets_Call{Call: _e.mock.On("ListUngroupedExpansionSets", ctx)}
}

func (_c *MockCatalogRepository_ListUngroupedExpansionSets_Call) Run(run func(ctx context.Context)) *MockCatalogRepository_ListUngroupedExpansionSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCatalogRepository_ListUngroupedExpansionSets_Call) Return(_a0 []entity.ExpansionSet, _a1 error) *MockCatalogRepository_ListUngroupedExpansionSets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_ListUngroupedExpansionSets_Call) RunAndReturn(run func(context.Context) ([]entity.ExpansionSet, error)) *MockCatalogRepository_ListUngroupedExpansionSets_Call {
	_c.Call.Return(run)
	return _c
}

// SearchCards provides a mock function with given fields: ctx, filter
func (_m *MockCatalogRepository) SearchCards(ctx context.Context, filter repository.CardFilter) ([]repository.CardResult, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for SearchCards")
	}

	var r0 []repository.CardResult
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CardFilter) ([]repository.CardResult, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CardFilter) []repository.CardResult); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.CardResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CardFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.CardFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCatalogRepository_SearchCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchCards'
type MockCatalogRepository_SearchCards_Call struct {
	*mock.Call
}

// SearchCards is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.CardFilter
func (_e *MockCatalogRepository_Expecter) SearchCards(ctx interface{}, filter interface{}) *MockCatalogRepository_SearchCards_Call {
	return &MockCatalogRepository_SearchCards_Call{Call: _e.mock.On("SearchCards", ctx, filter)}
}

func (_c *MockCatalogRepository_SearchCards_Call) Run(run func(ctx context.Context, filter repository.CardFilter)) *MockCatalogRepository_SearchCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.CardFilter))
	})
	return _c
}

func (_c *MockCatalogRepository_SearchCards_Call) Return(_a0 []repository.CardResult, _a1 int64, _a2 error) *MockCatalogRepository_SearchCards_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCatalogRepository_SearchCards_Call) RunAndReturn(run func(context.Context, repository.CardFilter) ([]repository.CardResult, int64, error)) *MockCatalogRepository_SearchCards_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCatalogRepository creates a new instance of MockCatalogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogRepository {
	mock := &MockCatalogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
