/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as CatalogSearchRouteImport } from './routes/catalog/search'
import { Route as AuthenticatedCollectionsIndexRouteImport } from './routes/_authenticated/collections/index'
import { Route as AuthenticatedCollectionsNewRouteImport } from './routes/_authenticated/collections/new'
import { Route as CatalogSetsExpansionSetIdRouteImport } from './routes/catalog/sets/$expansionSetId'
import { Route as AuthenticatedCollectionsCollectionIdIndexRouteImport } from './routes/_authenticated/collections/$collectionId/index'
import { Route as AuthenticatedCollectionsCollectionIdEditRouteImport } from './routes/_authenticated/collections/$collectionId/edit'
import { Route as CatalogCardsExpansionSetIdLocalIdRouteImport } from './routes/catalog/cards.$expansionSetId.$localId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSearchRoute = CatalogSearchRouteImport.update({
  id: '/catalog/search',
  path: '/catalog/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCollectionsIndexRoute =
  AuthenticatedCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsNewRoute =
  AuthenticatedCollectionsNewRouteImport.update({
    id: '/collections/new',
    path: '/collections/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const CatalogSetsExpansionSetIdRoute =
  CatalogSetsExpansionSetIdRouteImport.update({
    id: '/catalog/sets/$expansionSetId',
    path: '/catalog/sets/$expansionSetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCollectionsCollectionIdIndexRoute =
  AuthenticatedCollectionsCollectionIdIndexRouteImport.update({
    id: '/collections/$collectionId/',
    path: '/collections/$collectionId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsCollectionIdEditRoute =
  AuthenticatedCollectionsCollectionIdEditRouteImport.update({
    id: '/collections/$collectionId/edit',
    path: '/collections/$collectionId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const CatalogCardsExpansionSetIdLocalIdRoute =
  CatalogCardsExpansionSetIdLocalIdRouteImport.update({
    id: '/catalog/cards/$expansionSetId/$localId',
    path: '/catalog/cards/$expansionSetId/$localId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/catalog/search': typeof CatalogSearchRoute
  '/auth/': typeof AuthIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/catalog/sets/$expansionSetId': typeof CatalogSetsExpansionSetIdRoute
  '/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/collections/$collectionId/edit': typeof AuthenticatedCollectionsCollectionIdEditRoute
  '/catalog/cards/$expansionSetId/$localId': typeof CatalogCardsExpansionSetIdLocalIdRoute
  '/collections/$collectionId/': typeof AuthenticatedCollectionsCollectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/catalog/search': typeof CatalogSearchRoute
  '/auth': typeof AuthIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/catalog/sets/$expansionSetId': typeof CatalogSetsExpansionSetIdRoute
  '/collections': typeof AuthenticatedCollectionsIndexRoute
  '/collections/$collectionId/edit': typeof AuthenticatedCollectionsCollectionIdEditRoute
  '/catalog/cards/$expansionSetId/$localId': typeof CatalogCardsExpansionSetIdLocalIdRoute
  '/collections/$collectionId': typeof AuthenticatedCollectionsCollectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/health': typeof HealthRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/catalog/search': typeof CatalogSearchRoute
  '/auth/': typeof AuthIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/_authenticated/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/catalog/sets/$expansionSetId': typeof CatalogSetsExpansionSetIdRoute
  '/_authenticated/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/_authenticated/collections/$collectionId/edit': typeof AuthenticatedCollectionsCollectionIdEditRoute
  '/catalog/cards/$expansionSetId/$localId': typeof CatalogCardsExpansionSetIdLocalIdRoute
  '/_authenticated/collections/$collectionId/': typeof AuthenticatedCollectionsCollectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/health'
    | '/account'
    | '/inventory'
    | '/auth/login'
    | '/auth/register'
    | '/catalog/search'
    | '/auth/'
    | '/catalog/'
    | '/collections/new'
    | '/catalog/sets/$expansionSetId'
    | '/collections/'
    | '/collections/$collectionId/edit'
    | '/catalog/cards/$expansionSetId/$localId'
    | '/collections/$collectionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/account'
    | '/inventory'
    | '/auth/login'
    | '/auth/register'
    | '/catalog/search'
    | '/auth'
    | '/catalog'
    | '/collections/new'
    | '/catalog/sets/$expansionSetId'
    | '/collections'
    | '/collections/$collectionId/edit'
    | '/catalog/cards/$expansionSetId/$localId'
    | '/collections/$collectionId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/_authenticated'
    | '/health'
    | '/_authenticated/account'
    | '/_authenticated/inventory'
    | '/auth/login'
    | '/auth/register'
    | '/catalog/search'
    | '/auth/'
    | '/catalog/'
    | '/_authenticated/collections/new'
    | '/catalog/sets/$expansionSetId'
    | '/_authenticated/collections/'
    | '/_authenticated/collections/$collectionId/edit'
    | '/catalog/cards/$expansionSetId/$localId'
    | '/_authenticated/collections/$collectionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HealthRoute: typeof HealthRoute
  CatalogSearchRoute: typeof CatalogSearchRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  CatalogSetsExpansionSetIdRoute: typeof CatalogSetsExpansionSetIdRoute
  CatalogCardsExpansionSetIdLocalIdRoute: typeof CatalogCardsExpansionSetIdLocalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/search': {
      id: '/catalog/search'
      path: '/catalog/search'
      fullPath: '/catalog/search'
      preLoaderRoute: typeof CatalogSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/collections/': {
      id: '/_authenticated/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AuthenticatedCollectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/new': {
      id: '/_authenticated/collections/new'
      path: '/collections/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof AuthenticatedCollectionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/catalog/sets/$expansionSetId': {
      id: '/catalog/sets/$expansionSetId'
      path: '/catalog/sets/$expansionSetId'
      fullPath: '/catalog/sets/$expansionSetId'
      preLoaderRoute: typeof CatalogSetsExpansionSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/collections/$collectionId/': {
      id: '/_authenticated/collections/$collectionId/'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId/'
      preLoaderRoute: typeof AuthenticatedCollectionsCollectionIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/$collectionId/edit': {
      id: '/_authenticated/collections/$collectionId/edit'
      path: '/collections/$collectionId/edit'
      fullPath: '/collections/$collectionId/edit'
      preLoaderRoute: typeof AuthenticatedCollectionsCollectionIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/catalog/cards/$expansionSetId/$localId': {
      id: '/catalog/cards/$expansionSetId/$localId'
      path: '/catalog/cards/$expansionSetId/$localId'
      fullPath: '/catalog/cards/$expansionSetId/$localId'
      preLoaderRoute: typeof CatalogCardsExpansionSetIdLocalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedCollectionsNewRoute: typeof AuthenticatedCollectionsNewRoute
  AuthenticatedCollectionsIndexRoute: typeof AuthenticatedCollectionsIndexRoute
  AuthenticatedCollectionsCollectionIdEditRoute: typeof AuthenticatedCollectionsCollectionIdEditRoute
  AuthenticatedCollectionsCollectionIdIndexRoute: typeof AuthenticatedCollectionsCollectionIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedCollectionsNewRoute: AuthenticatedCollectionsNewRoute,
  AuthenticatedCollectionsIndexRoute: AuthenticatedCollectionsIndexRoute,
  AuthenticatedCollectionsCollectionIdEditRoute:
    AuthenticatedCollectionsCollectionIdEditRoute,
  AuthenticatedCollectionsCollectionIdIndexRoute:
    AuthenticatedCollectionsCollectionIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HealthRoute: HealthRoute,
  CatalogSearchRoute: CatalogSearchRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  CatalogSetsExpansionSetIdRoute: CatalogSetsExpansionSetIdRoute,
  CatalogCardsExpansionSetIdLocalIdRoute:
    CatalogCardsExpansionSetIdLocalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
