#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill. Usage: scripts/clerk-setup.sh [development|production]
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: Clerk dashboard setup (.scratch/security-hardening/issues/01).
# ──────────────────────────────────────────────────────────────────────────

MODE="${1:-development}"
case "$MODE" in
  development) KEY_PREFIX="test"; TOTAL_STAGES=9 ;;
  production)  KEY_PREFIX="live"; TOTAL_STAGES=6 ;;
  *) echo "usage: $0 [development|production]" >&2; exit 2 ;;
esac

for tool in curl jq openssl; do
  command -v "$tool" >/dev/null 2>&1 || { echo "error: '$tool' is required" >&2; exit 1; }
done
cd "$(git rev-parse --show-toplevel)"

# Re-run memory: finished stages live outside the repo, so nothing leaks into git.
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/cardstack"
STATE_FILE="$STATE_DIR/clerk-wizard-$MODE.state"
mkdir -p "$STATE_DIR"; touch "$STATE_FILE"

# Development keys go to the gitignored local env files. Live keys must never
# land in a repo checkout, so production keeps them in a private file instead.
if [[ "$MODE" == production ]]; then
  PROD_ENV="$STATE_DIR/clerk-production.env"
  (umask 077; touch "$PROD_ENV")
  FE_ENV="$PROD_ENV"; BE_ENV="$PROD_ENV"
else
  FE_ENV=frontend/.env; BE_ENV=backend/.env
fi

DASH="https://dashboard.clerk.com"
TEST_EMAIL="e2e+clerk_test@example.com"
CLAIMS_JSON='{ "email": "{{user.primary_email_address}}", "name": "{{user.full_name}}" }'

skip_done() {
  grep -qx "$1" "$STATE_FILE" || return 1
  note "Already done on an earlier run."
  confirm "Redo it?" && return 1
  return 0
}
mark_done() { grep -qx "$1" "$STATE_FILE" || echo "$1" >> "$STATE_FILE"; }

# load_var VAR FILE reads VAR from FILE, or sets it to "" (re-runs skip stages).
load_var() { printf -v "$1" '%s' "$(ENV_FILE="$2" _existing "$1" || true)"; }

# Plan-gated settings are recorded so the ticket can note them at the end.
ask_status() {
  local key="$1" label="$2" reply=""
  until [[ "$reply" =~ ^[ep] ]]; do
    printf '  %s%s%s: [e]nabled or [p]lan-gated (not available on your plan)? ' "$BOLD" "$label" "$RESET"
    read -r reply || true
  done
  grep -v "^setting:$key=" "$STATE_FILE" > "$STATE_FILE.tmp" || true
  mv "$STATE_FILE.tmp" "$STATE_FILE"
  if [[ "$reply" =~ ^e ]]; then
    echo "setting:$key=enabled" >> "$STATE_FILE"
  else
    echo "setting:$key=plan-gated" >> "$STATE_FILE"
    SKIPPED+=("plan-gated on Clerk: $label (note it in ticket 01)")
  fi
}

copy_clip() {
  if   command -v wl-copy  >/dev/null 2>&1; then printf '%s' "$1" | wl-copy
  elif command -v xclip    >/dev/null 2>&1; then printf '%s' "$1" | xclip -selection clipboard
  elif command -v pbcopy   >/dev/null 2>&1; then printf '%s' "$1" | pbcopy
  elif command -v clip.exe >/dev/null 2>&1; then printf '%s' "$1" | clip.exe
  else return 1; fi
}

# Frontend API host is the base64 payload of the publishable key, minus a "$".
fapi_host() {
  local b="${1#pk_*_}"
  while (( ${#b} % 4 )); do b+="="; done
  printf '%s' "$b" | base64 -d 2>/dev/null | tr -d '$' || true
}

# bapi METHOD PATH [JSON] calls Clerk's Backend API. The secret key goes through
# curl's stdin and the body through a private temp file, so neither shows in `ps`.
bapi() {
  local args=(-sS -K - -X "$1" -H 'Content-Type: application/json') body rc=0
  body=$(mktemp)
  printf '%s' "${3:-}" > "$body"
  if [[ -n "${3:-}" || "$1" != GET ]]; then args+=(--data-binary "@$body"); fi
  printf 'header = "Authorization: Bearer %s"\n' "$CLERK_SECRET_KEY" | curl "${args[@]}" "https://api.clerk.com$2" || rc=$?
  rm -f "$body"
  return "$rc"
}
find_user() {
  bapi GET "/v1/users?email_address=$(jq -rn --arg e "$TEST_EMAIL" '$e|@uri')" | jq -r '.[0].id // empty' 2>/dev/null || true
}
# bapi_jq METHOD PATH JSON FILTER prints FILTER's result or Clerk's error.
bapi_jq() {
  local out
  out=$(bapi "$1" "$2" "${3:-}") || { warn "request failed: $1 $2"; return 1; }
  jq -er "$4" <<<"$out" 2>/dev/null && return 0
  warn "Clerk answered: $(jq -c '.errors[0] | {code, message}' <<<"$out" 2>/dev/null || echo "unreadable response")"
  return 1
}

# Best-effort peek at what Clerk reports for this instance; never gates a stage.
fapi_env() { curl -fsS "https://$FAPI_HOST/v1/environment" 2>/dev/null || true; }

jwks_kids() { jq -c '[.keys[].kid] | sort' 2>/dev/null; }

load_var VITE_CLERK_PUBLISHABLE_KEY "$FE_ENV"
load_var CLERK_SECRET_KEY "$BE_ENV"
load_var E2E_CLERK_USER_EMAIL "$FE_ENV"
load_var E2E_CLERK_USER_PASSWORD "$FE_ENV"
FAPI_HOST=$(fapi_host "$VITE_CLERK_PUBLISHABLE_KEY")
CLERK_PROD_DOMAIN=""
if [[ "$MODE" == production ]]; then load_var CLERK_PROD_DOMAIN "$PROD_ENV"; fi

stage_keys() {
  local pk_kids sk_kids
  while :; do
    ENV_FILE="$FE_ENV" ask VITE_CLERK_PUBLISHABLE_KEY "Publishable key (pk_${KEY_PREFIX}_...):"
    ENV_FILE="$BE_ENV" ask_secret CLERK_SECRET_KEY "Secret key (sk_${KEY_PREFIX}_...):"
    FAPI_HOST=$(fapi_host "$VITE_CLERK_PUBLISHABLE_KEY")
    if [[ "$VITE_CLERK_PUBLISHABLE_KEY" == pk_${KEY_PREFIX}_* && "$CLERK_SECRET_KEY" == sk_${KEY_PREFIX}_* && -n "$FAPI_HOST" ]]; then
      pk_kids=$(curl -fsS "https://$FAPI_HOST/.well-known/jwks.json" 2>/dev/null | jwks_kids || true)
      sk_kids=$(bapi GET /v1/jwks 2>/dev/null | jwks_kids || true)
      if [[ -n "$pk_kids" && "$pk_kids" == "$sk_kids" ]]; then
        say "Both keys are valid and belong to the same instance ($FAPI_HOST)."
        break
      fi
      warn "Couldn't confirm the keys: they may be from different instances, or mistyped."
    else
      warn "Expected pk_${KEY_PREFIX}_... and sk_${KEY_PREFIX}_... keys from one ${MODE} instance."
    fi
    confirm "Enter them again?" || exit 1
  done
  ENV_FILE="$FE_ENV" write_env VITE_CLERK_PUBLISHABLE_KEY "$VITE_CLERK_PUBLISHABLE_KEY"
  ENV_FILE="$BE_ENV" write_env CLERK_SECRET_KEY "$CLERK_SECRET_KEY"
}

stage_email_password() {
  open_url "$DASH/~/user-authentication/user-and-authentication"
  step "Turn on 'Sign-up with email' with 'Require email address' on."
  step "Set 'Verify at sign-up' to 'Email verification code' (not link)."
  step "Turn on 'Sign in with email'."
  step "Open the Password tab and turn on 'Sign-up with password'. Clerk's sign-in then offers 'Forgot password?', which resets by emailed code (checked in a later stage)."
  step "Save."
  if [[ -n "$FAPI_HOST" ]]; then
    note "Best-effort read from Clerk (field names may drift):"
    fapi_env | jq -c '.user_settings.attributes | {email_address: (.email_address | {enabled, required, verifications}), password: (.password | {enabled})}' 2>/dev/null || note "couldn't read it automatically; trust the dashboard"
  fi
  pause "Saved? Press Enter."
}

stage_protection() {
  open_url "$DASH/~/protect/rules"
  step "'Lockout policy': enable (new instances default to 10 attempts, 1 hour)."
  step "'User enumeration protection': Manage, choose 'Bulk user enumeration protection', Save."
  step "'Bot sign-up protection': Enable, Save."
  say "If a row is missing or asks for a paid plan, answer 'p' for it below."
  ask_status lockout "Lockout policy"
  ask_status enumeration "Bulk user enumeration protection"
  ask_status bot "Bot sign-up protection"
}

stage_claims() {
  open_url "$DASH/~/sessions"
  step "Find 'Customize session token' and open the Claims editor."
  step "Replace its contents with this JSON, then Save:"
  printf '\n    %s\n\n' "$CLAIMS_JSON"
  copy_clip "$CLAIMS_JSON" && note "(copied to your clipboard)"
  pause "Saved? Press Enter."
}

echo_settings_summary() {
  grep '^setting:' "$STATE_FILE" >/dev/null 2>&1 || return 0
  printf '  %sSecurity settings, for the ticket comment:%s\n' "$BOLD" "$RESET"
  grep '^setting:' "$STATE_FILE" | sed 's/^setting:/    - /; s/=/: /'
  printf '\n'
}

# ── development instance ──────────────────────────────────────────────────

run_development() {
  banner "Clerk: development instance"

  stage "Create the instance and record its keys"
  if ! skip_done keys; then
    open_url "$DASH"
    step "Create application 'cardstack'. Enable only 'Email' and 'Google' as sign-in options."
    step "It opens a development instance. Open API keys (Configure → API keys)."
    step "Copy the Publishable key, then reveal and copy the Secret key."
    stage_keys
    mark_done keys
  fi

  stage "Google as the only social provider"
  if ! skip_done google; then
    open_url "$DASH/~/user-authentication/sso-connections"
    step "Make sure Google is the only connection, enabled for sign-up and sign-in."
    step "Leave 'Use custom credentials' off: development instances share Clerk's Google credentials."
    step "Remove any other provider."
    if [[ -n "$FAPI_HOST" ]]; then
      social=$(fapi_env | jq -r '[.user_settings.social // {} | to_entries[] | select(.value.enabled) | .key] | join(", ")' 2>/dev/null || true)
      if [[ "$social" == "oauth_google" ]]; then say "Clerk reports exactly one social provider: Google."
      elif [[ -n "$social" ]]; then warn "Clerk reports social providers: $social. Only Google should be enabled."
      else note "couldn't read the provider list automatically; trust the dashboard"; fi
    fi
    pause "Done? Press Enter."
    mark_done google
  fi

  stage "Email and password with mandatory email verification"
  if ! skip_done email; then stage_email_password; mark_done email; fi

  stage "Lockout, enumeration protection, bot protection"
  if ! skip_done protection; then stage_protection; mark_done protection; fi

  stage "Session token claims: email and name"
  if ! skip_done claims; then stage_claims; mark_done claims; fi

  stage "Create the end-to-end test user"
  if ! skip_done testuser; then
    say "Creating $TEST_EMAIL through Clerk's Backend API (no browser needed)."
    note "+clerk_test addresses never send mail and accept the code 424242."
    local uid verified pw
    uid=$(find_user)
    verified=false
    if [[ -n "$uid" && -n "$E2E_CLERK_USER_PASSWORD" ]]; then
      verified=$(bapi POST "/v1/users/$uid/verify_password" "$(P="$E2E_CLERK_USER_PASSWORD" jq -nc '{password: env.P}')" | jq -r '.verified // false' 2>/dev/null || echo false)
    fi
    if [[ "$verified" == true ]]; then
      say "Test user already exists and the saved password still works."
    else
      pw=$(openssl rand -hex 16)
      if [[ -n "$uid" ]]; then
        bapi_jq PATCH "/v1/users/$uid" "$(P="$pw" jq -nc '{password: env.P, skip_password_checks: true}')" '.id' >/dev/null || exit 1
        say "Test user existed; set a fresh password."
      else
        bapi_jq POST /v1/users "$(E="$TEST_EMAIL" P="$pw" jq -nc \
          '{email_address: [env.E], password: env.P, first_name: "E2E", last_name: "Test", skip_password_checks: true}')" '.id' >/dev/null || exit 1
        say "Created the test user."
      fi
      E2E_CLERK_USER_EMAIL="$TEST_EMAIL"; E2E_CLERK_USER_PASSWORD="$pw"
      ENV_FILE="$FE_ENV" write_env E2E_CLERK_USER_EMAIL "$E2E_CLERK_USER_EMAIL"
      ENV_FILE="$FE_ENV" write_env E2E_CLERK_USER_PASSWORD "$E2E_CLERK_USER_PASSWORD"
    fi
    mark_done testuser
  fi

  stage "Check the session token carries email and name"
  if ! skip_done tokencheck; then
    local uid sid jwt payload n
    uid=$(find_user)
    [[ -n "$uid" ]] || { warn "Test user not found; redo the previous stage."; exit 1; }
    while :; do
      sid=$(bapi_jq POST /v1/sessions "$(jq -nc --arg u "$uid" '{user_id:$u}')" '.id') || exit 1
      jwt=$(bapi_jq POST "/v1/sessions/$sid/tokens" "" '.jwt') || exit 1
      bapi POST "/v1/sessions/$sid/revoke" >/dev/null || true
      payload=$(printf '%s' "$jwt" | cut -d. -f2 | tr '_-' '/+')
      while (( ${#payload} % 4 )); do payload+="="; done
      payload=$(printf '%s' "$payload" | base64 -d 2>/dev/null || true)
      n=$(jq -c '{email, name}' <<<"$payload" | wc -c) || n=0
      say "Decoded token claims: $(jq -c '{iss, azp, email, name}' <<<"$payload")"
      say "Custom claims take ~$n bytes of Clerk's 1200-byte budget; whole token is ${#jwt} characters."
      if jq -e --arg e "$TEST_EMAIL" '.email == $e and (.name | type == "string" and length > 0)' <<<"$payload" >/dev/null 2>&1 && (( n <= 1200 )); then
        say "Email and name claims present and within the size limit."
        break
      fi
      warn "Email or name claim is missing, wrong or too large. Re-check the Sessions → Customize session token JSON."
      confirm "Retry the check?" || { SKIPPED+=("session token claims not verified (re-run this wizard)"); break; }
    done
    mark_done tokencheck
  fi

  stage "Sign in by hand: Google, verified email, unverified email"
  if ! skip_done manualcheck; then
    local portal="https://${FAPI_HOST%.clerk.accounts.dev}.accounts.dev"
    local stamp; stamp=$(date +%s)
    open_url "$portal/sign-up"
    note "This is Clerk's hosted Account Portal for your dev instance (Dashboard → Account Portal if the address doesn't load)."
    step "Google: 'Continue with Google' with your own account. You should end up signed in."
    confirm "Did Google sign-in work?" || SKIPPED+=("Google sign-in not confirmed")
    step "Verified email: sign up as check-$stamp+clerk_test@example.com with any password, then enter code 424242."
    confirm "Did that sign you in?" || SKIPPED+=("verified email sign-up not confirmed")
    step "Unverified email: sign up as nobody-$stamp@example.com. It should stop at the code screen. Do not enter a code."
    confirm "Did it stop there, with no signed-in state?" || SKIPPED+=("unverified sign-up may obtain a session: check email verification settings")
    step "Forgot password: on the sign-in page click 'Forgot password?'. It should offer to email a code. Don't finish it."
    confirm "Does it offer a reset code?" || SKIPPED+=("forgot-password not confirmed")
    mark_done manualcheck
  fi

  stage "Store the keys for CI"
  if ! skip_done github; then
    say "CI uses the development instance."
    set_secret CLERK_SECRET_KEY "$CLERK_SECRET_KEY"
    set_secret E2E_CLERK_USER_EMAIL "$E2E_CLERK_USER_EMAIL"
    set_secret E2E_CLERK_USER_PASSWORD "$E2E_CLERK_USER_PASSWORD"
    set_var VITE_CLERK_PUBLISHABLE_KEY "$VITE_CLERK_PUBLISHABLE_KEY"
    note "Local copies: $FE_ENV and $BE_ENV (gitignored). Committed examples hold placeholders only."
    mark_done github
  fi

  finish
  echo_settings_summary
}

# ── production instance ───────────────────────────────────────────────────

run_production() {
  banner "Clerk: production instance"
  warn "Needs the owner's domain from ticket 02 (a *.vercel.app address will not work)."

  stage "Create the production instance and its DNS records"
  if ! skip_done instance; then
    ENV_FILE="$PROD_ENV" ask CLERK_PROD_DOMAIN "Domain the site is served from (e.g. app.example.com):"
    ENV_FILE="$PROD_ENV" write_env CLERK_PROD_DOMAIN "$CLERK_PROD_DOMAIN"
    open_url "$DASH"
    step "Top of the dashboard: click 'Development' → 'Create production instance'."
    step "Choose 'Clone development instance settings'. Enter $CLERK_PROD_DOMAIN as the domain."
    step "Clerk lists the DNS records it needs (CNAMEs for clerk, accounts and email). Add them in Cloudflare → DNS."
    warn "Set every one of them to 'DNS only' (grey cloud). Clerk's DNS check fails behind Cloudflare's proxy."
    step "Back in Clerk, wait for the records and certificates to show as verified (can take a few minutes)."
    if command -v dig >/dev/null 2>&1; then
      for h in "clerk.$CLERK_PROD_DOMAIN" "accounts.$CLERK_PROD_DOMAIN"; do
        [[ -n "$(dig +short CNAME "$h")" ]] && say "DNS: $h resolves" || warn "DNS: no CNAME for $h yet"
      done
    fi
    pause "Records verified in Clerk? Press Enter."
    mark_done instance
  fi

  stage "Google with your own OAuth credentials"
  if ! skip_done google; then
    say "Production can't use Clerk's shared Google credentials, and SSO connections are not cloned."
    open_url "$DASH/~/user-authentication/sso-connections"
    step "Add connection → For all users → Google. Keep 'Enable for sign-up and sign-in' and 'Use custom credentials' on."
    step "Copy the 'Authorized Redirect URI' it shows; leave this tab open."
    open_url "https://console.cloud.google.com/apis/credentials"
    step "Create credentials → OAuth client ID → Web application. (If asked, configure the consent screen first.)"
    step "Paste the Authorized Redirect URI. Create, then copy the Client ID and Client secret."
    step "Paste both into Clerk's Google connection and Save."
    pause "Google connection saved? Press Enter."
    mark_done google
  fi

  stage "Confirm production matches development"
  if ! skip_done settings; then
    say "Cloning copies the user settings; re-check them here (SSO, integrations and paths do not clone)."
    stage_email_password
    stage_protection
    stage_claims
    note "Production can't mint test sessions, so the claims get their real check on the live site (ticket 13 smoke test)."
    mark_done settings
  fi

  stage "Record the live keys"
  if ! skip_done keys; then
    open_url "$DASH/~/api-keys"
    step "Make sure the dashboard shows the Production instance, then copy the live Publishable key and Secret key."
    stage_keys
    note "Saved in $PROD_ENV (mode 600, outside the repo), not in your checkout."
    mark_done keys
  fi

  stage "Railway: secret key and allowed frontend origins"
  if ! skip_done railway; then
    local env="${RAILWAY_ENVIRONMENT:-production}" svc="${RAILWAY_SERVICE:-cardstack}" origins current
    if command -v railway >/dev/null 2>&1 && railway whoami >/dev/null 2>&1; then
      current=$(railway variables -k -e "$env" -s "$svc" 2>/dev/null | sed -n 's/^APP_CLIENT_URLS=//p' || true)
      [[ -n "$current" ]] && say "Current APP_CLIENT_URLS: $current"
    fi
    warn "This REPLACES APP_CLIENT_URLS. Include every origin that must keep working, comma-separated, no trailing slash."
    ask origins "Frontend origin(s), e.g. https://$CLERK_PROD_DOMAIN:"
    if confirm "Set CLERK_SECRET_KEY and APP_CLIENT_URLS on Railway ($env / $svc)?"; then
      local manual=0
      for kv in "CLERK_SECRET_KEY=$CLERK_SECRET_KEY" "APP_CLIENT_URLS=$origins"; do
        if command -v railway >/dev/null 2>&1 && railway variables --set "$kv" -e "$env" -s "$svc" >/dev/null 2>&1; then
          printf '  %s✓ set%s Railway variable %s\n' "$GREEN" "$RESET" "${kv%%=*}"
        else
          manual=1
          warn "couldn't set ${kv%%=*} with the railway CLI"
        fi
      done
      if (( manual )); then
        open_url "https://railway.com/dashboard"
        step "Service $svc → Variables. CLERK_SECRET_KEY is in $PROD_ENV; APP_CLIENT_URLS is: $origins"
        pause "Set by hand? Press Enter."
      fi
      mark_done railway
    fi
  fi

  stage "Vercel: publishable key"
  if ! skip_done vercel; then
    open_url "https://vercel.com/dashboard"
    step "Project → Settings → Environment Variables → Add."
    step "Name: VITE_CLERK_PUBLISHABLE_KEY"
    step "Value: $VITE_CLERK_PUBLISHABLE_KEY"
    step "Environments: Production only. Preview and Development keep the pk_test key."
    note "Vite bakes VITE_* into the bundle, so redeploy the frontend after saving."
    pause "Saved? Press Enter."
    mark_done vercel
  fi

  finish
  echo_settings_summary
}

"run_$MODE"
