#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill. Usage: scripts/cloudflare-setup.sh
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: Cloudflare, R2 and hosting setup (.scratch/security-hardening/issues/02).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

for tool in curl jq openssl dig base64 xargs; do
  command -v "$tool" >/dev/null 2>&1 || { echo "error: '$tool' is required" >&2; exit 1; }
done
cd "$(git rev-parse --show-toplevel)"

# Every value here is production-grade, so it lives in a private file outside
# the repo, never in backend/.env (an EDGE_SECRET there would switch the edge
# check on for local development once ticket 04 lands).
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/cardstack"
STATE_FILE="$STATE_DIR/cloudflare-wizard.state"
CF_ENV="$STATE_DIR/cloudflare.env"
mkdir -p "$STATE_DIR"; touch "$STATE_FILE"
(umask 077; touch "$CF_ENV")
ENV_FILE="$CF_ENV"

CF="https://dash.cloudflare.com"
EDGE_HEADER="X-Edge-Secret"
TEST_KEY="_wizard/test.png"
# Smallest valid PNG (1x1), enough to prove upload, public read and resizing.
TEST_PNG_B64="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="

skip_done() {
  grep -qx "$1" "$STATE_FILE" || return 1
  note "Already done on an earlier run."
  confirm "Redo it?" && return 1
  return 0
}
mark_done() { grep -qx "$1" "$STATE_FILE" || echo "$1" >> "$STATE_FILE"; }
unmark_done() {
  grep -vx "$1" "$STATE_FILE" > "$STATE_FILE.tmp" || true
  mv "$STATE_FILE.tmp" "$STATE_FILE"
}

copy_clip() {
  if   command -v wl-copy  >/dev/null 2>&1; then printf '%s' "$1" | wl-copy
  elif command -v xclip    >/dev/null 2>&1; then printf '%s' "$1" | xclip -selection clipboard
  elif command -v pbcopy   >/dev/null 2>&1; then printf '%s' "$1" | pbcopy
  elif command -v clip.exe >/dev/null 2>&1; then printf '%s' "$1" | clip.exe
  else return 1; fi
}

load() { printf -v "$1" '%s' "$(_existing "$1" || true)"; }
load DOMAIN; load R2_BUCKET; load R2_ACCOUNT_ID; load R2_ACCESS_KEY_ID; load R2_SECRET_ACCESS_KEY
load EDGE_SECRET; load RATE_LIMIT

set_hosts() { CDN_HOST="cdn.$DOMAIN"; API_HOST="api.$DOMAIN"; }
set_hosts

# bail MSG stops the wizard with a visible reason (the library's SKIPPED list is
# only printed by finish, which an exit never reaches).
bail() { warn "$1"; exit 1; }

on_cloudflare() {
  local ns; ns=$(dig +short NS "$DOMAIN" 2>/dev/null || true)
  [[ "${ns,,}" == *cloudflare.com* ]]
}

# need VAR: a stage that depends on an earlier one stops with a clear message.
need() {
  [[ -n "${!1}" ]] || { warn "$1 is missing: redo the earlier stage that records it."; exit 1; }
}

# r2 METHOD KEY [FILE] talks to R2's S3 API with curl's built-in SigV4 and prints
# the HTTP status. The key pair goes through curl's stdin, never `ps`.
R2_BODY=$(mktemp); trap 'rm -f "$R2_BODY"' EXIT
r2() {
  local args=(-sS -o "$R2_BODY" -w '%{http_code}' -K - --aws-sigv4 'aws:amz:auto:s3' -X "$1")
  if [[ -n "${3:-}" ]]; then args+=(-T "$3" -H 'Content-Type: image/png'); fi
  printf 'user = "%s:%s"\n' "$R2_ACCESS_KEY_ID" "$R2_SECRET_ACCESS_KEY" |
    curl "${args[@]}" "https://$R2_ACCOUNT_ID.r2.cloudflarestorage.com/$R2_BUCKET/$2" 2>/dev/null || printf '000'
}

r2_put_test() {
  local png status
  png=$(mktemp)
  printf '%s' "$TEST_PNG_B64" | base64 -d > "$png"
  status=$(r2 PUT "$TEST_KEY" "$png")
  rm -f "$png"
  [[ "$status" == 200 ]] || { warn "R2 upload answered HTTP $status: $(head -c 200 "$R2_BODY" | tr '\n' ' ')"; return 1; }
}

# hget URL HEADER prints "STATUS|header-value" from a plain GET (no redirects followed).
hget() {
  local out status value
  out=$(curl -sS -D - -o /dev/null -H 'Accept: image/avif,image/webp,*/*' "$1" 2>/dev/null | tr -d '\r') || true
  status=$(printf '%s' "$out" | sed -n '1s/^HTTP[^ ]* \([0-9]*\).*/\1/p')
  value=$(printf '%s' "$out" | grep -i "^$2:" | head -n1 | cut -d: -f2- | sed 's/^ *//' || true)
  printf '%s|%s' "${status:-000}" "$value"
}

stage_zone() {
  local old_domain="$DOMAIN" k
  while :; do
    ask DOMAIN "Your domain, e.g. example.com (no www, no https://):"
    [[ "$DOMAIN" =~ ^[a-z0-9]([a-z0-9.-]*[a-z0-9])?\.[a-z]{2,}$ ]] && break
    warn "That doesn't look like a bare domain name."
  done
  if [[ -n "$old_domain" && "$DOMAIN" != "$old_domain" ]]; then
    for k in bucket r2key images apidomain edgerule raterule railway vercel; do unmark_done "$k"; done
    warn "Domain changed: every stage that depends on it will run again."
  fi
  write_env DOMAIN "$DOMAIN"
  set_hosts
  if on_cloudflare; then
    say "$DOMAIN already uses Cloudflare nameservers. Nothing to do."
    return
  fi
  open_url "$CF/?to=/:account/add-site"
  step "Add a site: enter $DOMAIN, choose the Free plan."
  step "Cloudflare shows two nameservers. At your registrar, replace the domain's nameservers with them."
  warn "If the domain already serves a live site, review the DNS records Cloudflare imported before switching."
  step "Wait for Cloudflare to say the site is Active (minutes to hours)."
  until on_cloudflare; do
    warn "No Cloudflare nameservers visible for $DOMAIN yet."
    confirm "Check again?" || bail "$DOMAIN is not on Cloudflare yet: re-run this wizard once it is active."
  done
  say "Confirmed: $DOMAIN uses Cloudflare nameservers."
}

stage_bucket() {
  local old_bucket="$R2_BUCKET" k
  open_url "$CF/?to=/:account/r2/overview"
  step "Create bucket. Name it as you like (for example cardstack-images); leave location on Automatic."
  while :; do
    ask R2_BUCKET "Bucket name:"
    [[ -n "$R2_BUCKET" ]] && break
    warn "A bucket name is required."
  done
  if [[ -n "$old_bucket" && "$R2_BUCKET" != "$old_bucket" ]]; then
    for k in r2key images railway; do unmark_done "$k"; done
    warn "Bucket changed: the access key, image check and Railway variables will run again."
  fi
  write_env R2_BUCKET "$R2_BUCKET"
  step "Open the bucket → Settings → Custom Domains → Add: $CDN_HOST. Pick the $DOMAIN zone, then Connect domain."
  step "Leave 'Public Development URL' (r2.dev) disabled: the custom domain is the only public door."
  step "Wait until the domain's status reads Active."
  pause "Active? Press Enter."
}

stage_r2_key() {
  open_url "$CF/?to=/:account/r2/api-tokens"
  step "Manage API tokens → Create Account API token (wording may differ slightly; any token that does the job below is fine)."
  step "Permissions: Object Read & Write. Specify bucket: $R2_BUCKET only. Create."
  step "Copy the Access Key ID and the Secret Access Key now (the secret is shown once)."
  step "Also copy the Account ID: it is the hex part of the S3 endpoint, https://<ACCOUNT_ID>.r2.cloudflarestorage.com."
  while :; do
    ask R2_ACCOUNT_ID "Account ID:"
    ask R2_ACCESS_KEY_ID "Access Key ID:"
    ask_secret R2_SECRET_ACCESS_KEY "Secret Access Key:"
    if [[ -n "$R2_ACCOUNT_ID" && -n "$R2_ACCESS_KEY_ID" && -n "$R2_SECRET_ACCESS_KEY" ]] && r2_put_test; then
      say "Upload works: the key can write to $R2_BUCKET."
      break
    fi
    confirm "Enter the credentials again?" || bail "R2 credentials not verified: re-run this wizard."
  done
  write_env R2_ACCOUNT_ID "$R2_ACCOUNT_ID"
  write_env R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
  write_env R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"
  unmark_done railway
}

stage_transformations() {
  open_url "$CF/?to=/:account/images/transformations"
  step "Select the $DOMAIN zone and enable transformations."
  step "Leave 'Resize from any origin' OFF: transformations should only run on images in this zone, so outsiders can't spend the 5,000-per-month free allowance."
  pause "Enabled? Press Enter."
  local orig xform
  while :; do
    r2_put_test || { confirm "Upload failed. Retry?" && continue || exit 1; }
    orig=$(hget "https://$CDN_HOST/$TEST_KEY" content-type)
    xform=$(hget "https://$CDN_HOST/cdn-cgi/image/width=240,format=auto/$TEST_KEY" cf-resized)
    say "Original through $CDN_HOST: HTTP ${orig%%|*}, ${orig#*|}"
    say "Transformed variant: HTTP ${xform%%|*}, cf-resized: ${xform#*|}"
    if [[ "${orig%%|*}" == 200 && "${xform%%|*}" == 200 ]]; then
      if [[ -n "${xform#*|}" ]]; then
        say "Both the original and a transformed variant load."
      else
        warn "Loaded, but Cloudflare sent no cf-resized header, so I can't prove it was transformed."
        confirm "Open it yourself and check it loads: https://$CDN_HOST/cdn-cgi/image/width=240,format=auto/$TEST_KEY. Does it?" || continue
      fi
      break
    fi
    warn "Not serving yet (a new custom domain or setting can take a minute)."
    confirm "Check again?" || { SKIPPED+=("image host not verified at https://$CDN_HOST (re-run this wizard)"); return 1; }
  done
  r2 DELETE "$TEST_KEY" >/dev/null || true
}

stage_api_domain() {
  open_url "https://railway.com/dashboard"
  step "Service api → Settings → Networking → + Custom Domain: $API_HOST (target port: the app's port, 8080, if asked)."
  step "Railway shows a CNAME target and a TXT record. You need BOTH."
  open_url "$CF/?to=/:account/:zone/dns/records"
  step "Add the CNAME: name 'api', target = Railway's value, Proxy status ON (orange cloud)."
  step "Add the TXT record exactly as Railway shows it (name and value). Without it Railway answers 404."
  open_url "$CF/?to=/:account/:zone/ssl-tls"
  step "SSL/TLS → Overview → set the mode to 'Full'. Not 'Full (strict)': Railway's docs say strict does not work behind the proxy."
  step "Back in Railway, wait for the domain's green check and 'Cloudflare proxy detected'."
  local h
  while :; do
    h=$(hget "https://$API_HOST/health" cf-ray)
    if [[ "${h%%|*}" == 200 && -n "${h#*|}" ]]; then
      say "https://$API_HOST/health answers 200 through Cloudflare (cf-ray ${h#*|})."
      break
    fi
    warn "https://$API_HOST/health answered HTTP ${h%%|*}$([[ -n "${h#*|}" ]] && echo ', via Cloudflare')."
    note "404: TXT record missing or not verified. 52x/525/526: SSL mode or Railway certificate. 000: DNS not propagated."
    confirm "Check again?" || { SKIPPED+=("api subdomain not verified at https://$API_HOST (re-run this wizard)"); return 1; }
  done
}

stage_edge_rule() {
  if [[ -z "$EDGE_SECRET" ]]; then
    EDGE_SECRET=$(openssl rand -hex 32)
    write_env EDGE_SECRET "$EDGE_SECRET"
    unmark_done railway
  else
    say "Reusing the edge secret from an earlier run (a new one would desync Cloudflare from Railway)."
  fi
  say "Cloudflare will add the header $EDGE_HEADER to every request for $API_HOST."
  copy_clip "$EDGE_SECRET" && note "(the secret is on your clipboard)" || note "(no clipboard tool found: the secret is in $CF_ENV)"
  open_url "$CF/?to=/:account/:zone/rules/overview"
  step "Create rule → Request Header Transform Rules."
  step "Name: api-edge-secret. Filter: 'Custom filter expression' → Edit expression → paste:"
  printf '\n    (http.host eq "%s")\n\n' "$API_HOST"
  step "Modify request header → Set static. Header name: $EDGE_HEADER. Value: paste the secret."
  step "Deploy."
  note "Scoped to $API_HOST so the cdn host never gets the secret. Ticket 04 is what checks the header; nothing rejects requests yet."
  pause "Deployed? Press Enter."
  SKIPPED+=("edge-secret header rule is unverified until ticket 04 ships: then confirm the raw Railway address rejects requests without it")
}

stage_rate_rule() {
  local n code body
  ask RATE_LIMIT "Requests allowed per IP per 10 seconds [100]:"
  [[ "$RATE_LIMIT" =~ ^[0-9]+$ ]] || { warn "Not a number: using 100."; RATE_LIMIT=100; }
  write_env RATE_LIMIT "$RATE_LIMIT"
  say "The free plan allows ONE rate rule: period 10 s, action Block, duration 10 s, counted per IP."
  warn "Free-plan expressions can't match on hostname, so the rule covers the whole zone. Scope it to API paths so image loads on $CDN_HOST never count."
  open_url "$CF/?to=/:account/:zone/security/security-rules"
  step "Create rule → Rate limiting rules. Name: api-per-ip."
  step "When incoming requests match → Edit expression → paste:"
  printf '\n    (starts_with(http.request.uri.path, "/catalog")) or (starts_with(http.request.uri.path, "/collections")) or (starts_with(http.request.uri.path, "/inventory"))\n\n'
  note "If the free plan rejects that expression, use the builder instead: Path 'starts with' each of /catalog, /collections, /inventory, joined by OR."
  step "Characteristics: IP (preset). Requests: $RATE_LIMIT. Period: 10 seconds."
  step "Action: Block. Duration: 10 seconds. Deploy."
  note "/health is left out on purpose, so the host's monitor is never blocked. Keep the frontend's own domain's DNS record 'DNS only' (grey cloud), or its /catalog pages count too."
  pause "Deployed? Press Enter."
  n=$((RATE_LIMIT + 60))
  while :; do
    confirm "Run a burst of $n requests at https://$API_HOST/catalog/series now? Your IP will be blocked for ~10 s." || {
      SKIPPED+=("rate rule not burst-tested (re-run this wizard)"); return 1; }
    yes "https://$API_HOST/catalog/series" | head -n "$n" |
      xargs -P 40 -n1 curl -s -o /dev/null -w '%{http_code}\n' | sort | uniq -c | sed 's/^/    /' || true
    body=$(curl -s "https://$API_HOST/catalog/series" || true)
    code=$(curl -s -o /dev/null -w '%{http_code}' "https://$API_HOST/catalog/series" || true)
    if [[ "$code" == 429 && "$body" == *1015* ]]; then
      say "Cloudflare's rate rule fired (HTTP 429, error 1015)."
      break
    fi
    warn "No Cloudflare 429 seen (last status $code, body: ${body:0:120}). The rule may not match, or the burst was too slow."
    note "Waiting 10 s for any block to clear."
    sleep 10
  done
}

stage_railway() {
  local block image_base gate=1
  image_base="https://$CDN_HOST"
  say "Does the frontend already call the API at https://$API_HOST (Vercel VITE_API_BASE_URL)?"
  note "The edge secret blocks the raw Railway address, which breaks a frontend still pointing at it. Ticket 13 turns it on at cutover."
  confirm "Include EDGE_SECRET now?" || gate=0
  block=$(printf 'R2_ACCOUNT_ID=%s\nR2_ACCESS_KEY_ID=%s\nR2_SECRET_ACCESS_KEY=%s\nR2_BUCKET=%s\nIMAGE_BASE_URL=%s\n' \
    "$R2_ACCOUNT_ID" "$R2_ACCESS_KEY_ID" "$R2_SECRET_ACCESS_KEY" "$R2_BUCKET" "$image_base")
  if (( gate )); then block+=$'\n'"EDGE_SECRET=$EDGE_SECRET"; else
    SKIPPED+=("EDGE_SECRET not set on Railway yet: add it at cutover (ticket 13 step 5); it is saved in $CF_ENV")
  fi
  open_url "https://railway.com/dashboard"
  step "Service api → Variables → Raw Editor. Paste the block below at the end and Update Variables (this redeploys)."
  printf '\n%s\n\n' "$(printf '%s' "$block" | sed -E 's/^(R2_SECRET_ACCESS_KEY|EDGE_SECRET)=.*/\1=<secret>/')"
  if copy_clip "$block"; then
    note "(the whole block, real secrets included, is on your clipboard: clear it after pasting)"
  else
    note "(no clipboard tool found: copy the real values from $CF_ENV)"
  fi
  warn "Railway pull-request environments are forked from this one and may inherit these variables."
  step "If a PR environment is open, check its Variables: EDGE_SECRET and the R2 keys must not be there. Remove them if they are."
  note "Ticket 04 (and 05) must make the preview workflow unset them; recorded in ticket 02's comments."
  pause "Variables saved in Railway? Press Enter."
  (( gate ))  # a withheld EDGE_SECRET leaves the stage open, so a re-run offers it again
}

stage_vercel() {
  open_url "https://vercel.com/dashboard"
  step "Project → Settings → Environment Variables → Add."
  step "Name: VITE_IMAGE_HOST"
  step "Value: https://$CDN_HOST"
  step "Environments: Production and Preview (previews fork production data, so their images are hosted too)."
  note "VITE_* is baked into the bundle: redeploy the frontend after saving."
  note "VITE_API_BASE_URL is not changed here; ticket 13 repoints it at https://$API_HOST at cutover."
  pause "Saved? Press Enter."
}

banner "Cloudflare, R2 and hosting"

stage "Put the domain on Cloudflare"
if ! skip_done zone; then stage_zone; mark_done zone; fi
need DOMAIN; set_hosts

stage "R2 bucket and the cdn subdomain"
if ! skip_done bucket; then stage_bucket; mark_done bucket; fi
need R2_BUCKET

stage "R2 access key limited to the bucket"
if ! skip_done r2key; then stage_r2_key; mark_done r2key; fi
need R2_SECRET_ACCESS_KEY

stage "Image transformations and the image host check"
if ! skip_done images; then stage_transformations && mark_done images; fi

stage "The api subdomain behind Cloudflare"
if ! skip_done apidomain; then stage_api_domain && mark_done apidomain; fi

stage "Edge secret header on the api subdomain"
if ! skip_done edgerule; then stage_edge_rule; mark_done edgerule; fi
need EDGE_SECRET

stage "Per-IP rate rule"
if ! skip_done raterule; then stage_rate_rule && mark_done raterule; fi

stage "Railway: R2 credentials, image base address, edge secret"
if ! skip_done railway; then stage_railway && mark_done railway; fi

stage "Vercel: image host"
if ! skip_done vercel; then stage_vercel; mark_done vercel; fi

finish
note "Values kept in $CF_ENV (mode 600, outside the repo)."
printf '\n'
