// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeProviders() (*Providers, func(), error) {
	dataSources, cleanup, err := ProvideDataSource()
	if err != nil {
		return nil, nil, err
	}
	auth := ProvideAuthConfig()
	userStore := ProvideUserStore(dataSources)
	sessionStore := ProvideSessionStore(dataSources)
	refreshTokenStore := ProvideRefreshTokenStore(dataSources)
	transactor := ProvideTransactor(dataSources)
	sessionCache := ProvideSessionCache()
	authKit, cleanup2, err := ProvideAuthKit(auth, userStore, sessionStore, refreshTokenStore, transactor, sessionCache)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	services := ProvideServices(authKit)
	providers := &Providers{
		DataSources: dataSources,
		Services:    services,
	}
	return providers, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	DataSourceSet,
	RepositorySet,
	AuthSet,
	ServiceSet, wire.Struct(new(Providers), "*"),
)
