// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeProviders() (*Providers, func(), error) {
	dataSources, cleanup, err := ProvideDataSource()
	if err != nil {
		return nil, nil, err
	}
	tokenVerifier := ProvideTokenVerifier()
	userRepository := ProvideUserRepository(dataSources)
	identityCache := ProvideIdentityCache()
	userService := ProvideUserService(dataSources, userRepository, identityCache)
	imageHost := ProvideImageHost()
	catalogService := ProvideCatalogService(dataSources, imageHost)
	collectionService := ProvideCollectionService(dataSources)
	inventoryService := ProvideInventoryService(dataSources, imageHost)
	services := ProvideServices(tokenVerifier, userService, catalogService, collectionService, inventoryService)
	providers := &Providers{
		DataSources: dataSources,
		Services:    services,
	}
	return providers, func() {
		cleanup()
	}, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	DataSourceSet,
	RepositorySet,
	AuthSet,
	ServiceSet, wire.Struct(new(Providers), "*"),
)
