// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeProviders() (*Providers, func(), error) {
	dataSources, cleanup, err := ProvideDataSource()
	if err != nil {
		return nil, nil, err
	}
	tokenVerifier, err := ProvideTokenVerifier()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRepository := ProvideUserRepository(dataSources)
	userService := ProvideUserService(dataSources, userRepository)
	catalogService := ProvideCatalogService(dataSources)
	collectionService := ProvideCollectionService(dataSources)
	inventoryService := ProvideInventoryService(dataSources)
	services := ProvideServices(tokenVerifier, userService, catalogService, collectionService, inventoryService)
	providers := &Providers{
		DataSources: dataSources,
		Services:    services,
	}
	return providers, func() {
		cleanup()
	}, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	DataSourceSet,
	RepositorySet,
	AuthSet,
	ServiceSet, wire.Struct(new(Providers), "*"),
)
